### ISSUE TITLE
add an 'x' button to close the error messages popup

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash#1403]
Currently you have to click on the devtools icon and then toggle errors button.

**Comment by chriddyp** [comment]
In this UI
![image](https://user-images.githubusercontent.com/1280389/92668461-b48e7180-f2c3-11ea-9612-1c7e5875ec16.png)

**Comment by Biswa5812** [comment]
Where is this particular UI available, under which folder?

**Comment by chriddyp** [comment]
@Biswa5812 - It's in here: https://github.com/plotly/dash/tree/dev/dash-renderer/src/components/error/FrontEnd

**Comment by chriddyp** [comment]
@Biswa5812 - Let us know if you end up taking a look at this one! This would be a good first issue to get started contributing to Dash.

**Comment by Sable-20** [comment]
Quick update for anyone looking at this
https://github.com/plotly/dash/tree/dev/dash/dash-renderer/src/components/error/FrontEnd 
issue can be found here, there was a update adding /dash/

**Comment by Alfred-Emmanuel** [comment]
Please has this been fixed? if no, could i be assigned to this?

**Comment by gvwilson** [comment]
@Alfred-Emmanuel sure - if you would like to submit a PR we would be very happy to review it. thank you - @gvwilson

**Comment by Alfred-Emmanuel** [comment]
Hi @gvwilson , I am running into some errors while trying to setup the project,  could you please let me know the prerequisites i need to have installed before being able to setup the project locally? i have nodejs and python installed already

**Comment by gvwilson** [comment]
hi @Alfred-Emmanuel - are you using the instructions in `CONTRIBUTING.md`? If so, where is it failing for you? (If you can paste a log into a comment here that would help.)

**Comment by Alfred-Emmanuel** [comment]
Yes, i am using the instructions in the CONTRIBUTING.md, everything was going well until i ran "npm run build", the log is quite long but this is it below

npm run build

> build
> run-s private::build.*


> private::build.components
> python dash/development/update_components.py 'all'

npx lerna exec --concurrency 3 --scope='{dash-core-components,dash-html-components,dash-table}' -- npm i
lerna notice cli v6.6.2
lerna info versioning independent
lerna notice filter including "{dash-core-components,dash-html-components,dash-table}"
lerna info filter [ '{dash-core-components,dash-html-components,dash-table}' ]
lerna info Executing command in 3 packages: "npm i"
npm warn deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm warn deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm warn deprecated @babel/plugin-proposal-private-methods@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-methods instead.
npm warn deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm warn deprecated @babel/plugin-proposal-object-rest-spread@7.12.1: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm warn deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm warn deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm warn deprecated figgy-pudding@3.5.2: This module is no longer supported.
npm warn deprecated @babel/plugin-proposal-private-property-in-object@7.21.11: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-property-in-object instead.
npm warn deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm warn deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm warn deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm warn deprecated har-validator@5.1.5: this library is no longer supported
npm warn deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm warn deprecated trim@0.0.1: Use String.prototype.trim() instead
npm warn deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm warn deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm warn deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm warn deprecated jssha@2.4.2: jsSHA versions < 3.0.0 will no longer receive feature updates
npm warn deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when 
needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm warn deprecated puppeteer@1.20.0: < 21.5.0 is no longer supported
npm warn deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
lerna success exec Executed command in 3 packages: "npm i"

🟢 Finished installing npm dependencies for component packages: {dash-core-components,dash-html-comp onents,dash-table} 🟢
npx lerna exec --concurrency 3 --scope='{dash-core-components,dash-html-components,dash-table}' -- npm run build
🛑 lerna notice cli v6.6.2
lerna info versioning independent
lerna notice filter including "{dash-core-components,dash-html-components,dash-table}"
lerna info filter [ '{dash-core-components,dash-html-components,dash-table}' ]
lerna info Executing command in 3 packages: "npm run build"
node:fs:2346
    return binding.writeFileUtf8(
                   ^

.react.js'ENT: no such file or directory, open 'C:\Users\PC\dash\components\dash-html-components\src\components\A
    at Object.writeFileSync (node:fs:2346:20)
    at writeComponents (C:\Users\PC\dash\components\dash-html-components\scripts\generate-components.js:361:12)
    at Object.<anonymous> (C:\Users\PC\dash\components\dash-html-components\scripts\generate-components.js:384:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\PC\\dash\\components\\dash-html-components\\src\\components\\A\r.react.js'
}

lerna ERR! npm run build exited 1 in 'dash-html-components'
lerna ERR! npm run build exited 1 in 'dash-html-components'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
(node:16044) [DEP_WEBPACK_RULE_LOADER_OPTIONS_STRING] DeprecationWarning: Using a string as loader options is deprecated (ruleSet[1].rules[3].use[2].options)
(Use `node --trace-deprecation ...` to show where the warning was created)
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
'dash-generate-components' is not recognized as an internal or external command,
operable program or batch file.
ERROR: "build:backends" exited with 1.
'dash-generate-components' is not recognized as an internal or external command,
operable program or batch file.
ERROR: "private::build:backends" exited with 1.

🚨 Finished updating component packages: {dash-core-components,dash-html-components,dash-table} (status=1) 🚨
ERROR: "private::build.components" exited with 1.

**Comment by gvwilson** [comment]
@Coding-with-Adam @archmoj either of you run into this?

**Comment by Coding-with-Adam** [comment]
Hi @gvwilson I have not run into this, no.

**Comment by Alfred-Emmanuel** [comment]
Oh well, i'm just going to try to find a way to get past it. i'd let you know how it goes

**Comment by gvwilson** [comment]
@Alfred-Emmanuel we might have a simpler solution for you by the middle of next week - I'll give you a shout when I know more. thanks - @gvwilson

**Comment by Alfred-Emmanuel** [comment]
Hi @gvwilson, i'm sending this message as a reminder about the solution

**Comment by gvwilson** [comment]
Hi @Alfred-Emmanuel - my apologies, but we don't have one for you yet. As soon as we merge some upstream changes in plotly.js, this ought to get simpler, but we need to fix the bugs in that first. My apologies for the delay...

**Comment by Gannu456** [comment]
is this issue already solved or i can work upon this?

**Comment by kenshima4** [comment]
I think this should be closed? It exists on dev. ![Image](https://github.com/user-attachments/assets/088cdff7-f8dc-4305-bff9-f5ec1cd276ae)
