### ISSUE TITLE
TextArea has incorrect value type for n_clicks_timestamp

### ISSUE THREAD

**Issue by nandan-sridhar** [plotly/dash#1451]
**Environment**

- OS: Ubuntu 16.04
- Browser: chrome
- Python 3.8.6

```
dash                           1.17.0
dash-core-components           1.13.0
dash-core-components-ppeterson 0.43.2
dash-daq                       0.5.0
dash-html-components           1.1.1
dash-renderer                  1.8.3
dash-table                     4.11.0
```
**Descripton**
I was running the following example code:

```
import dash
from dash.dependencies import Input, Output, State
import dash_html_components as html
import dash_core_components as dcc

app = dash.Dash(__name__)

app.layout = html.Div([
    dcc.Textarea(
        id='textarea-state-example',
        value='Textarea content initialized\nwith multiple lines of text',
        style={'width': '100%', 'height': 200},
    ),
    html.Button('Submit', id='textarea-state-example-button', n_clicks=0),
    html.Div(id='textarea-state-example-output', style={'whiteSpace': 'pre-line'})
])

@app.callback(
    Output('textarea-state-example-output', 'children'),
    [Input('textarea-state-example-button', 'n_clicks')],
    [State('textarea-state-example', 'value')]
)
def update_output(n_clicks, value):
    if n_clicks > 0:
        return 'You have entered: \n{}'.format(value)

if __name__ == '__main__':
    app.run_server(debug=True)
```

When using the dcc.TextArea module, after clicking the text box, the following error shows:
```
Invalid argument `n_clicks_timestamp` passed into Textarea with ID "textarea-state-example".
Expected `number`.
Was supplied type `date`.
Value provided: "2020-10-31T21:01:46.992Z"

(This error originated from the built-in JavaScript code that runs Dash apps. Click to see the full stack trace or open your browser's console.)
Error: Invalid argument `n_clicks_timestamp` passed into Textarea with ID "textarea-state-example".

Expected `number`.

Was supplied type `date`.

Value provided: "2020-10-31T21:01:46.992Z"

    at propTypeErrorHandler (http://127.0.0.1:8050/_dash-component-suites/dash_renderer/dash_renderer.v1_8_2m1601265813.dev.js:98421:9)

    at CheckedComponent (http://127.0.0.1:8050/_dash-component-suites/dash_renderer/dash_renderer.v1_8_2m1601265813.dev.js:92763:77)

    at renderWithHooks (http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_8_2m1601265813.13.0.js:14960:20)

    at updateFunctionComponent (http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_8_2m1601265813.13.0.js:17193:22)

    at beginWork (http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_8_2m1601265813.13.0.js:18778:18)

    at HTMLUnknownElement.callCallback (http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_8_2m1601265813.13.0.js:182:16)

    at Object.invokeGuardedCallbackDev (http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_8_2m1601265813.13.0.js:231:18)

    at invokeGuardedCallback (http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_8_2m1601265813.13.0.js:286:33)

    at beginWork$1 (http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_8_2m1601265813.13.0.js:23369:9)

    at performUnitOfWork (http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_8_2m1601265813.13.0.js:22323:14)

```

**Expected behavior**

The n_clicks_timestamp looks like it is the formatted string of a python datetime object. The expected value should be a numeric value.

**Comment by AnnMarieW** [comment]
I tried the example app and it ran without any errors.  It looks like it's been fixed since at least dash 2.5.
