### ISSUE TITLE
[BUG] Temporary failure in name resolution (x86_64-conda_cos6-linux-gnu)

### ISSUE THREAD

**Issue by raybellwaves** [plotly/dash#1480]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Please provide us your environment so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                      1.17.0
dash-auth                 1.4.1
dash-bootstrap-components 0.10.7
dash-core-components      1.13.0
dash-html-components      1.1.1
dash-renderer             1.8.3
dash-table                4.11.0
explainerdashboard        0.2.13.2
jupyter-dash              0.3.1
```

**Describe the bug**

Unable to run an app. Get 

```
Dash is running on http://x86_64-conda_cos6-linux-gnu:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/ray/local/bin/anaconda3/envs/test_env/lib/python3.8/site-packages/dash/dash.py", line 1716, in run_server
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "/home/ray/local/bin/anaconda3/envs/test_env/lib/python3.8/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/home/ray/local/bin/anaconda3/envs/test_env/lib/python3.8/site-packages/werkzeug/serving.py", line 1030, in run_simple
    s.bind(server_address)
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

**Expected behavior**

App to run

**Code**

```
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.express as px
import pandas as pd

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

# assume you have a "long-form" data frame
# see https://plotly.com/python/px-arguments/ for more options
df = pd.DataFrame({
    "Fruit": ["Apples", "Oranges", "Bananas", "Apples", "Oranges", "Bananas"],
    "Amount": [4, 1, 2, 2, 4, 5],
    "City": ["SF", "SF", "SF", "Montreal", "Montreal", "Montreal"]
})

fig = px.bar(df, x="Fruit", y="Amount", color="City", barmode="group")

app.layout = html.Div(children=[
    html.H1(children='Hello Dash'),

    html.Div(children='''
        Dash: A web application framework for Python.
    '''),

    dcc.Graph(
        id='example-graph',
        figure=fig
    )
])

if __name__ == '__main__':
    app.run_server(debug=True)
```

**OS**

I'm using python via conda on my linux. I imagine x86_64-conda_cos6-linux-gnu is the culprit as that is normally localhost (on my windows for example).

Env:

```
$ conda create -n test_env python=3.8
$ conda activate test_env
$ pip install explainerdashboard
```

```
(test_env) ray@ray-MS-7B43:~$ uname -a
Linux ray-MS-7B43 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
(test_env) ray@ray-MS-7B43:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**Comment by RoboTums** [comment]
Same Problem on my Ubuntu 20 machine. 

The error i get from running app.py: 
```
Dash is running on http://x86_64-conda-linux-gnu:8050/

 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "app.py", line 35, in <module>
    app.run_server(debug=True)
  File "/home/owleyes/anaconda3/envs/bio_seq/lib/python3.6/site-packages/dash/dash.py", line 1716, in run_server
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "/home/owleyes/anaconda3/envs/bio_seq/lib/python3.6/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/home/owleyes/anaconda3/envs/bio_seq/lib/python3.6/site-packages/werkzeug/serving.py", line 1030, in run_simple
    s.bind(server_address)
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

I've tried to ``` conda update dash``` , which didn't work. Is there a specific version I could unroll to?

**Comment by ransonr** [comment]
You can get around this by passing `host='127.0.0.1'` to `app.run_server` (credit to [this answer](https://stackoverflow.com/a/61007094)). The `host` argument for `run_server` defaults to the `HOST` environment variable, which is apparently being set by the conda initialization script.

**Comment by raybellwaves** [comment]
Thanks @ransonr

**Comment by summa-code** [comment]
This is occurring in latest Dash 2.18.1.  Doing this app.run_server(host='0.0.0.0' did nothing

**Comment by Aishwary13** [comment]
Still I am getting below issue:
Dash is running on http://x86_64-conda-linux-gnu:8050/

 * Serving Flask app 'app'
 * Debug mode: off
Temporary failure in name resolution


I used this too.
if __name__ == '__main__':
    dash_app.run_server(host='127.0.0.1', port='8050')

**Comment by RainyBlue-w** [comment]
I have also met this problem:
```bash
$ python -m stintev --port=8056
0.0.0.0
Dash is running on http://x86_64-conda-linux-gnu:8056/

 * Serving Flask app 'stintev.server'
 * Debug mode: off
Name or service not known
```

I have set the `host` param of `app.run()` to `0.0.0.0`, but it makes nothing changed.

**Comment by zndr27** [comment]
Yeah all dash 2.18 versions dont work. Had to go back to 2.17.1 which was the latest one that works.

**Comment by zndr27** [comment]
Can someone help with this please? It is still the case that 2.18 versions don't work with docker on Ubuntu 24.10 and have to revert to 2.17.1

**Comment by antonkulaga** [comment]
Why the hell it was closed? the issue is totally valid for the latest version of dash
