### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mitchhit234** [plotly/dash#1676]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                      1.20.0
dash-bootstrap-components 0.12.2
dash-core-components      1.16.0
dash-html-components      1.1.3
dash-renderer             1.9.1
dash-table                4.11.3
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Fedora 33
    - Browser: Firefox
    - Version 89

**Describe the bug**

Using an App Callback to update the values of a dash table. Whenever I enter a Df.to_dict('records') as is, the table generates fine. However, whenever I remove rows from that dataframe and then try to update the table, I get an infinite recursion error. This only happens with one of my dataframes, but the tough part about it is that a dataframe with all those original values + more worked with the update, so this new frame should too. Through much debugging and stepping through the dash code I still can't come to a conclusion, its hard to find where the infinite recursion even happens because I was able to step through the entire process myself in very little time.

**Expected behavior**

New datatable updated output without giving infinite recursion error

**Screenshots**

Debug Output:
RangeError: Maximum call stack size exceeded

    at RegExp.[Symbol.replace] (<anonymous>)

    at String.replace (<anonymous>)

    at tx.trim (http://localhost:8050/_dash-component-suites/dash_renderer/polyfill@7.v1_9_1m1617900226.8.7.min.js:1:34947)

    at parseInt (http://localhost:8050/_dash-component-suites/dash_renderer/polyfill@7.v1_9_1m1617900226.8.7.min.js:1:29631)

    at s.t.handleResize (http://localhost:8050/_dash-component-suites/dash_table/async-table.js:2:286415)

    at s.t.handleResize (http://localhost:8050/_dash-component-suites/dash_table/async-table.js:2:286480)

    at s.t.handleResize (http://localhost:8050/_dash-component-suites/dash_table/async-table.js:2:286480)

    at s.t.handleResize (http://localhost:8050/_dash-component-suites/dash_table/async-table.js:2:286480)

    at s.t.handleResize (http://localhost:8050/_dash-component-suites/dash_table/async-table.js:2:286480)

    at s.t.handleResize (http://localhost:8050/_dash-component-suites/dash_table/async-table.js:2:286480)

Here is the dict that is supposed to be updated to the data value of the table
[{'DATE': 'Apr 14 2021', 'DESCRIPTION': 'DEPOSIT   IRS  TREAS  ', 'CREDIT': '1400.00'}, {'DATE': 'Apr 05 2021', 'DESCRIPTION': 'DEPOSIT  TAX REF  IRS  TREAS  ', 'CREDIT': '2582.00'}]

**Comment by avm19** [comment]
Same problem, version 2.18. Someone please have a look, I believe I narrowed it down.

The bug does not come from Dash DataTable update, but the update aggravates it. When the update callback is enabled, I see many (tens or hundreds) `InternalError: too much recursion` errors in browser's debugger. Without the update callback, there is just one (actually, two separate entries). So the infinite recursion is already there, and is dealt with by the browser. But the presence of the callback somehow causes an infinite loop of infinite recursion, and this is when the browser gets overwhelmed.

This is the infinite loop re-entry point:
https://github.com/plotly/dash/blob/e6a98461245510e97c417a8042ebfe657f7f5e6e/components/dash-table/src/dash-table/components/ControlledTable/index.tsx#L445-L456

This looks like a trivial programming mistake, which is easy to correct. What's happening is `currentTableWidth == "auto"`, `currentWidth` and `nextWidth` are both `NaN`. The value `nextWidth === previousWidth` becomes the value of `cycle` in the next recursive call. The true value of `cycle` is meant to prevent infinite recursion, and the programmer intended to set it true whenever `nextWidth` and `previousWidth` hold identical values. But `NaN === NaN` evaluates to `false`. So a fix would be would be something like 
`(nextWidth === previousWidth) || (isNaN(nextWidth) && isNaN(nextWidth))`.

If this makes sense, will someone please fix it. @Marc-Andre-Rivet 's name pops in git blame :-)

**Comment by avm19** [comment]
Here is a practical interim solution, which helped in my case. Others might find it useful.

I have 2 Dash DataTables, which were updated from a single callback, as follows. This caused the infinite recursion.
```Python
@callback(
    Output("tbl1", "data"),
    Output("tbl2", "data"),
    Input("interval", "n_intervals"),
)
def update(n):
	...
```

If I split the above into two callbacks, the infinite recursion problem seems to disappear:
```Python
@callback(
    Output("tbl1", "data"),
    Input("interval", "n_intervals"),
)
def update_1(n):
	...

@callback(
    Output("tbl2", "data"),
    Input("interval", "n_intervals"),
)
def update_2(n):
	...
```

It's funny that if I remove these callbacks completely, the infinite recursion comes back, but only as one or two errors, which do not affect user experience at all. Also, `prevent_initial_call=True` has an interesting effect. It must be some sort of a race condition, which is present by default, resolved by separate callbacks and made fatal by having a single callback. The behaviour I observe can be summarised as follows:

No infinite recursion:
- separate callbacks 

"Single" infinite recursion:
- separate callbacks with `prevent_initial_call=True`
- unified callback with `prevent_initial_call=True`
- no callbacks at all

Infinite loop of infinite recursion (fatal):
- unified callback

**Comment by KitauchiShinji** [comment]
I encountered the same problem (dash: 2.18.2).
`currentWidth` is `NaN` because of `currentTableWidth = "auto"` and it is looping infinitely.
