### ISSUE TITLE
ModuleNotFoundError: No module named 'dash.development'; 'dash' is not a package

### ISSUE THREAD

**Issue by sreelakshmig009** [plotly/dash#1689]
I'm trying to run this code in my local system for creating a simple sidebar with dash. 

This is my code : 

```
import dash
import dash_bootstrap_components as dbc
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

SIDEBAR_STYLE = {
    "position": "fixed",
    "top": 0,
    "left": 0,
    "bottom": 0,
    "width": "16rem",
    "padding": "2rem 1rem",
    "background-color": "#00008b",
}


CONTENT_STYLE = {
    "margin-left": "18rem",
    "margin-right": "2rem",
    "padding": "2rem 1rem",
}

sidebar = html.Div(
    [
        html.H2("Sidebar", className="display-4"),
        html.Hr(),
        dbc.Nav(
            [
                dbc.NavLink("Home", href="/", active="exact"),
                dbc.NavLink("Page 1", href="/page-1", active="exact"),
                dbc.NavLink("Page 2", href="/page-2", active="exact"),
            ],
            vertical=True,
            pills=True,
        ),
    ],
    style=SIDEBAR_STYLE,
)

content = html.Div(id="page-content", style=CONTENT_STYLE)

app.layout = html.Div([dcc.Location(id="url"), sidebar, content])


@app.callback(Output("page-content", "children"), [Input("url", "pathname")])
def render_page_content(pathname):
    if pathname == "/":
        return html.P("This is the content of the home page!")
    elif pathname == "/page-1":
        return html.P("This is the content of page 1. Yay!")
    elif pathname == "/page-2":
        return html.P("Oh cool, this is page 2!")
    # If the user tries to reach a different page, return a 404 message
    return dbc.Jumbotron(
        [
            html.H1("404: Not found", className="text-danger"),
            html.Hr(),
            html.P(f"The pathname {pathname} was not recognised..."),
        ]
    )


if __name__ == "__main__":
    app.run_server(port=8888)
```

And this is the error I'm getting even though I have all the dependencies downloaded in my system

```
Traceback (most recent call last):
  File "C:/Users/G Sreelakshmi/Desktop/dash.py", line 1, in <module>
    import dash
  File "C:/Users/G Sreelakshmi/Desktop\dash.py", line 2, in <module>
    import dash_bootstrap_components as dbc
  File "E:\PYTHON 3.9\lib\site-packages\dash_bootstrap_components\__init__.py", line 6, in <module>
    from dash_bootstrap_components import _components
  File "E:\PYTHON 3.9\lib\site-packages\dash_bootstrap_components\_components\__init__.py", line 1, in <module>
    from .Alert import Alert
  File "E:\PYTHON 3.9\lib\site-packages\dash_bootstrap_components\_components\Alert.py", line 3, in <module>
    from dash.development.base_component import Component, _explicitize_args
ModuleNotFoundError: No module named 'dash.development'; 'dash' is not a package
```

**Comment by anders-kiaer** [comment]
Try renaming `dash.py` in `C:/Users/G Sreelakshmi/Desktop` to something else, e.g. `dash_app.py` 🙂

**Comment by sreelakshmig009** [comment]
Oh yeah I tried that but it didn't resolve my issue

**Comment by sreelakshmig009** [comment]
That seemed to resolve the issue. Quite stupid of me to raise it as a bug. Thank you @anders-kiaer
