### ISSUE TITLE
[BUG] When running the example 3 of dash tutorial part 5, got error

### ISSUE THREAD

**Issue by isCopyman** [plotly/dash#1770]
**Describe your context**

```
win10
python 3.9
dash                 2.0.0
dash-core-components 2.0.0
dash-html-components 2.0.0
dash-table           5.0.0
debugpy              1.4.3
decorator            5.1.0
defusedxml           0.7.1
entrypoints          0.3
Flask                2.0.1
Flask-Caching        1.10.1
Flask-Compress       1.10.1
```
    - OS: [win10]
    - Browser [chrome]

**Describe the bug**

When running example 3 of the dash tutorial part 5, got this error:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\63036\Anaconda3\envs\yuketang\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\63036\Anaconda3\envs\yuketang\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\63036\Anaconda3\envs\yuketang\lib\site-packages\werkzeug\serving.py", line 948, in inner
    srv = make_server(
  File "C:\Users\63036\Anaconda3\envs\yuketang\lib\site-packages\werkzeug\serving.py", line 778, in make_server
    raise ValueError("cannot have a multithreaded and multi process server.")
ValueError: cannot have a multithreaded and multi process server.
my code:
```
my code:
```
import json
import os
import copy
import time
import datetime
import dash
from dash import dcc
from dash import html
from dash.dependencies import Input, Output, State
import plotly.express as px
import pandas as pd
import numpy as np
from flask_caching import Cache

external_stylesheets = [
    # Dash CSS
    'https://codepen.io/chriddyp/pen/bWLwgP.css',
    # Loading screen CSS
    'https://codepen.io/chriddyp/pen/brPBPO.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)
server = app.server

CACHE_CONFIG = {
    "CACHE_TYPE": "FileSystemCache",  # Flask-Caching related configs
    'CACHE_DIR': 'cache'
}
cache = Cache()
cache.init_app(app.server, config=CACHE_CONFIG)

N = 100

df = pd.DataFrame({
    'category': (
        (['apples'] * 5 * N) +
        (['oranges'] * 10 * N) +
        (['figs'] * 20 * N) +
        (['pineapples'] * 15 * N)
    )
})
df['x'] = np.random.randn(len(df['category']))
df['y'] = np.random.randn(len(df['category']))

app.layout = html.Div([
    dcc.Dropdown(
        id='dropdown',
        options=[{'label': i, 'value': i} for i in df['category'].unique()],
        value='apples'
    ),
    html.Div([
        html.Div(dcc.Graph(id='graph-1'), className="six columns"),
        html.Div(dcc.Graph(id='graph-2'), className="six columns"),
    ], className="row"),
    html.Div([
        html.Div(dcc.Graph(id='graph-3'), className="six columns"),
        html.Div(dcc.Graph(id='graph-4'), className="six columns"),
    ], className="row"),

    # signal value to trigger callbacks
    dcc.Store(id='signal')
])


# perform expensive computations in this "global store"
# these computations are cached in a globally available
# redis memory store which is available across processes
# and for all time.
@cache.memoize()
def global_store(value):
    # simulate expensive query
    print('Computing value with {}'.format(value))
    time.sleep(5)
    return df[df['category'] == value]


def generate_figure(value, figure):
    fig = copy.deepcopy(figure)
    filtered_dataframe = global_store(value)
    fig['data'][0]['x'] = filtered_dataframe['x']
    fig['data'][0]['y'] = filtered_dataframe['y']
    fig['layout'] = {'margin': {'l': 20, 'r': 10, 'b': 20, 't': 10}}
    return fig


@app.callback(Output('signal', 'data'), Input('dropdown', 'value'))
def compute_value(value):
    # compute value and send a signal when done
    global_store(value)
    return value


@app.callback(Output('graph-1', 'figure'), Input('signal', 'data'))
def update_graph_1(value):
    # generate_figure gets data from `global_store`.
    # the data in `global_store` has already been computed
    # by the `compute_value` callback and the result is stored
    # in the global redis cached
    return generate_figure(value, {
        'data': [{
            'type': 'scatter',
            'mode': 'markers',
            'marker': {
                'opacity': 0.5,
                'size': 14,
                'line': {'border': 'thin darkgrey solid'}
            }
        }]
    })


@app.callback(Output('graph-2', 'figure'), Input('signal', 'data'))
def update_graph_2(value):
    return generate_figure(value, {
        'data': [{
            'type': 'scatter',
            'mode': 'lines',
            'line': {'shape': 'spline', 'width': 0.5},
        }]
    })


@app.callback(Output('graph-3', 'figure'), Input('signal', 'data'))
def update_graph_3(value):
    return generate_figure(value, {
        'data': [{
            'type': 'histogram2d',
        }]
    })


@app.callback(Output('graph-4', 'figure'), Input('signal', 'data'))
def update_graph_4(value):
    return generate_figure(value, {
        'data': [{
            'type': 'histogram2dcontour',
        }]
    })


if __name__ == '__main__':
    app.run_server(debug=True,processes=6)
```
**Expected behavior**
When setting processes = 1, got no errors but can't run callbacks parallel.

**Screenshots**

![image](https://user-images.githubusercontent.com/25970108/134216572-6a057cfd-a3be-480b-84b9-549f24996950.png)

**Comment by nickmelnikov82** [comment]
The documentation has already been updated.
Quote from the dash [tutorial](https://dash.plotly.com/sharing-data-between-callbacks#example-3---caching-and-signaling): 
```
As we are running the server with multiple processes, we set threaded to False. 
A Flask server can't be be both multi-process and multi-threaded.
```
So either `processes=6,threaded=False` or `processes=1,threaded=True`

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
