### ISSUE TITLE
Flexible callbacks failing validation

### ISSUE THREAD

**Issue by KuechlerO** [plotly/dash#1881]
Hi guys,

thx for the fantastic work with Dash. I love it! <3

However, I have great trouble with the flexible callback support, that is introduced with Dash 2.0.0.
When I use dictionaries to capture the inputs and outputs for the callback function, the dash validation cancels me...
The error message says **"'dict' object has no attribute 'component_property'"**.
I have no clue what I did wrong, since I followed exactly the instructions on [here](https://dash.plotly.com/flexible-callback-signatures).

Here's my minimal example:
```
@app.callback(
    output=dict(x=Output("positioned_toast_div", "children")),
    inputs=dict(a=Input("btn_start_points_add", "n_clicks"))
)
def callback(a):
    return dict(x="Test")
```

    
This is my exception thread:
```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/oliverkuchler/miniconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/oliverkuchler/miniconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/oliverkuchler/Studium/Apollo/aging-database/Django-files/apollo_pgsql_db/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/oliverkuchler/Studium/Apollo/aging-database/Django-files/apollo_pgsql_db/venv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/Users/oliverkuchler/Studium/Apollo/aging-database/Django-files/apollo_pgsql_db/venv/lib/python3.7/site-packages/django/core/management/base.py", line 423, in check
    databases=databases,
  File "/Users/oliverkuchler/Studium/Apollo/aging-database/Django-files/apollo_pgsql_db/venv/lib/python3.7/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/oliverkuchler/Studium/Apollo/aging-database/Django-files/apollo_pgsql_db/venv/lib/python3.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/Users/oliverkuchler/Studium/Apollo/aging-database/Django-files/apollo_pgsql_db/venv/lib/python3.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/Users/oliverkuchler/Studium/Apollo/aging-database/Django-files/apollo_pgsql_db/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 412, in check
    for pattern in self.url_patterns:
  File "/Users/oliverkuchler/Studium/Apollo/aging-database/Django-files/apollo_pgsql_db/venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/oliverkuchler/Studium/Apollo/aging-database/Django-files/apollo_pgsql_db/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/oliverkuchler/Studium/Apollo/aging-database/Django-files/apollo_pgsql_db/venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/oliverkuchler/Studium/Apollo/aging-database/Django-files/apollo_pgsql_db/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/oliverkuchler/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/oliverkuchler/Studium/Apollo/aging-database/Django-files/apollo_pgsql_db/apollo_pgsql_db/urls.py", line 18, in <module>
    from DashApp import FullScreenNetwork_Setup, SimpleNetwork, GeneNetwork    # Needed to make sure that the Dash-App is found
  File "/Users/oliverkuchler/Studium/Apollo/aging-database/Django-files/apollo_pgsql_db/DashApp/FullScreenNetwork_Setup.py", line 385, in <module>
    inputs=dict(a=Input("btn_start_points_add", "n_clicks"))
  File "/Users/oliverkuchler/Studium/Apollo/aging-database/Django-files/apollo_pgsql_db/venv/lib/python3.7/site-packages/django_plotly_dash/dash_wrapper.py", line 331, in callback
    _args, _kwargs
  File "/Users/oliverkuchler/Studium/Apollo/aging-database/Django-files/apollo_pgsql_db/venv/lib/python3.7/site-packages/dash/dependencies.py", line 360, in handle_callback_args
    validate_callback(validate_outputs, inputs, states, flat_args, types)
  File "/Users/oliverkuchler/Studium/Apollo/aging-database/Django-files/apollo_pgsql_db/venv/lib/python3.7/site-packages/dash/_validate.py", line 40, in validate_callback
    validate_callback_arg(arg)
  File "/Users/oliverkuchler/Studium/Apollo/aging-database/Django-files/apollo_pgsql_db/venv/lib/python3.7/site-packages/dash/_validate.py", line 51, in validate_callback_arg
    ).format(arg.component_property)
AttributeError: 'dict' object has no attribute 'component_property'
```

My environment:
```
dash                      2.0.0
dash-bootstrap-components 1.0.2
dash-core-components      2.0.0
dash-cytoscape            0.3.0
dash-html-components      2.0.0
dash-renderer             1.9.1
dash-table                5.0.0
django-plotly-dash        1.6.6
```

_Originally posted by @KuechlerO in https://github.com/plotly/dash/issues/1691#issuecomment-1005930583_

**Comment by alexcjohnson** [comment]
Does it work for you if you make a plain dash app? I suspect `django-plotly-dash` needs to be updated for dash 2.0, but that would need to be addressed over there: https://github.com/GibbsConsulting/django-plotly-dash

**Comment by KuechlerO** [comment]
> Does it work for you if you make a plain dash app? I suspect `django-plotly-dash` needs to be updated for dash 2.0, but that would need to be addressed over there: https://github.com/GibbsConsulting/django-plotly-dash

Thx for the quick reply. 
And yes, it's true. Starting a plain dash app in the same environment causes no problems. Thus I agree with you: The problem is probably with `django-plotly-dash`.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
