### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by viksuper555** [plotly/dash#1888]
**Describe your context**
Dash app with long_callbacks managed by CeleryLongCallbackManager with Redis cache. 
OS is Ubuntu on local machine.

in init.py:
CELERY_BROKER_URL = f"redis://:{CACHE_REDIS_PASSWORD}@{CACHE_REDIS_HOST}:{CACHE_REDIS_PORT}/{CELERY_BROKER_DB}"
CELERY_RESULT_BACKEND = f"redis://:{CACHE_REDIS_PASSWORD}@{CACHE_REDIS_HOST}:{CACHE_REDIS_PORT}/{CELERY_RESULT_BACKEND_DB}"

celery = Celery(__name__, broker=CELERY_BROKER_URL, include=['dashboard', 'dashboard.tasks'], backend=CELERY_RESULT_BACKEND)

long_callback_manager = CeleryLongCallbackManager(celery, cache_by=[lambda: uuid4()])

dashapp = dash.Dash(...
        long_callback_manager=long_callback_manager)

This is the decorator of the callback in callbacks.py:
@dashapp.long_callback(
        Output('output1', 'value'),
        (
            Input('input1', 'value')
        )
    )
@cache.memoize()
def callback1()

```
dash                      2.0.0      
dash-bootstrap-components 1.0.0      
dash-core-components      2.0.0      
dash-html-components      2.0.0      
dash-table                5.0.0  
```
**Describe the bug**

After invocation the long_callback doesn't return a result. It throws the following exception instead:

[ERROR/ForkPoolWorker-1] Error closing cursor
Traceback (most recent call last):
  File "/usr/lib/python3.8/encodings/utf_16_le.py", line 15, in decode
    def decode(input, errors='strict'):
  File "/home/viktor/projects/MyProject/venv/lib/python3.8/site-packages/billiard/common.py", line 119, in _shutdown_cleanup
    sys.exit(-(256 - signum))
  File "/home/viktor/projects/MyProject/venv/lib/python3.8/site-packages/billiard/pool.py", line 283, in exit
    return _exit(status)
SystemExit: -241

**Expected behavior**

Expect the long_callback to return result correctly.

**Comment by viksuper555** [comment]
Hi, issue is getting obsolete and we have changed to using a different approach. 
I will close this one, since it was not documented well.
