### ISSUE TITLE
favicon.ico request now causes an Exception 

### ISSUE THREAD

**Issue by ned2** [plotly/dash#189]
It looks like this commit #181 and specifically [this line](https://github.com/plotly/dash/commit/2c07f191bac881b37d8705aaa4374d04a796f9cb#diff-228c9aefac729977642672aa1416bacaL278) which removed *args and **kwargs from Dash's index function signature is now causing an exception on the initial page load of an app due to the `/facivon.ico` request being handled by the index method, thereby getting a `path=favicon.ico` parameter.

As mentioned in #152 this is caused by Dash serving the index route as a catchall for otherwise unmatched routes. 

```
Traceback (most recent call last):
  File "/home/nejl/.pyenv/versions/3.6.1/envs/dash/lib/python3.6/site-packages/flask/app.py", line 1998, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/nejl/.pyenv/versions/3.6.1/envs/dash/lib/python3.6/site-packages/flask/app.py", line 1986, in wsgi_app
    response = self.handle_exception(e)
  File "/home/nejl/.pyenv/versions/3.6.1/envs/dash/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nejl/.pyenv/versions/3.6.1/envs/dash/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/nejl/.pyenv/versions/3.6.1/envs/dash/lib/python3.6/site-packages/flask/app.py", line 1983, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nejl/.pyenv/versions/3.6.1/envs/dash/lib/python3.6/site-packages/flask/app.py", line 1615, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nejl/.pyenv/versions/3.6.1/envs/dash/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nejl/.pyenv/versions/3.6.1/envs/dash/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/nejl/.pyenv/versions/3.6.1/envs/dash/lib/python3.6/site-packages/flask/app.py", line 1613, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nejl/.pyenv/versions/3.6.1/envs/dash/lib/python3.6/site-packages/flask/app.py", line 1599, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: index() got an unexpected keyword argument 'path'

```

**Comment by chriddyp** [comment]
ah, right, of course. yeah, let's add that back
