### ISSUE TITLE
None type has no attribute 'traverse'

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash#195]
I just started seeing
```
2018-01-10T06:17:39.964092563Z app[web.1]: Traceback (most recent call last):
2018-01-10T06:17:39.964099180Z app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
2018-01-10T06:17:39.964103966Z app[web.1]:     response = self.full_dispatch_request()
2018-01-10T06:17:39.964107809Z app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1607, in full_dispatch_request
2018-01-10T06:17:39.964111993Z app[web.1]:     self.try_trigger_before_first_request_functions()
2018-01-10T06:17:39.964115877Z app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1654, in try_trigger_before_first_request_functions
2018-01-10T06:17:39.964123526Z app[web.1]:     func()
2018-01-10T06:17:39.964127506Z app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/dash/dash.py", line 554, in _setup_server
2018-01-10T06:17:39.964131756Z app[web.1]:     self._generate_scripts_html()
2018-01-10T06:17:39.964136209Z app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/dash/dash.py", line 244, in _generate_scripts_html
2018-01-10T06:17:39.964140344Z app[web.1]:     self.scripts.get_all_scripts() +
2018-01-10T06:17:39.964144036Z app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/dash/resources.py", line 123, in get_all_scripts
2018-01-10T06:17:39.964148288Z app[web.1]:     return self._resources.get_all_resources()
2018-01-10T06:17:39.964152068Z app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/dash/resources.py", line 56, in get_all_resources
2018-01-10T06:17:39.964156151Z app[web.1]:     self.get_inferred_resources() + self._resources
2018-01-10T06:17:39.964160074Z app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/dash/resources.py", line 84, in get_inferred_resources
2018-01-10T06:17:39.964164094Z app[web.1]:     for t in layout.traverse():
2018-01-10T06:17:39.964167914Z app[web.1]: AttributeError: 'NoneType' object has no attribute 'traverse'
```

in one of my examples:

```
import dash
import dash_auth
import dash_core_components as dcc
import dash_html_components as html
import os
import plotly.plotly as py
import dash_auth

import dash
from dash.dependencies import Input, Output
import dash_core_components as dcc
import dash_html_components as html
import datetime
from flask_caching import Cache
import pandas as pd
import time
import uuid


import config

app = dash.Dash(__name__)

# Checks if running inside Plotly On-Premise environment
if 'DYNO' in os.environ:
    if config.PATH_BASED_ROUTING:
        if config.DASH_APP_NAME == 'name-of-your-dash-app':
             raise Exception('Please enter the name of your dash app inside config.py')
        app.config.requests_pathname_prefix = '/{}/'.format(
            config.DASH_APP_NAME
        )

if config.PATH_BASED_ROUTING:
    APP_URL = '{}/{}'.format(
        config.PLOTLY_DASH_DOMAIN.strip('/'),
        config.DASH_APP_NAME,
    )
else:
    APP_URL = '{}://{}.{}'.format(
        config.PLOTLY_DASH_DOMAIN.split('://')[0],
        config.DASH_APP_NAME,
        config.PLOTLY_DASH_DOMAIN.split('://')[1].strip('/')
    )

# Expose the server variable
server = app.server

# Serve JS and CSS files locally instead of from global CDN
# app.scripts.config.serve_locally = True
# app.css.config.serve_locally = True

app = dash.Dash()
cache = Cache(app.server, config={
    'CACHE_TYPE': 'filesystem',
    'CACHE_DIR': 'cache-directory',
    'CACHE_THRESHOLD': 50  # should be equal to maximum number of active users
})

@cache.memoize()
def query_data(session_id):
    df = pd.DataFrame({'a': [datetime.datetime.now()], session_id: [session_id]})
    return df.to_json()


def dataframe(session_id):
    return pd.read_json(query_data(session_id))

def serve_layout():
    session_id = str(uuid.uuid4())
    df = dataframe(session_id)
    return html.Div([
        html.Div(session_id, id='session-id', style={'display': 'none'}),
        dcc.Dropdown(id='dropdown', value='a', options=[
            {'label': i, 'value': i} for i in ['a', 'b', 'c', 'd']
        ]),
        html.Pre(id='output')
    ])

app.layout = serve_layout


@app.callback(Output('output', 'children'),
              [Input('dropdown', 'value'),
               Input('session-id', 'children')])
def display_value(value, session_id):
    df = dataframe(session_id)
    return df.to_csv()


if __name__ == '__main__':
    app.run_server(debug=True)
```

I'm not sure why or if this is an user error or a bug with dash, but I'm posting this here for future reference

**Comment by chriddyp** [comment]
user error, `dash` was declared twice. remove the second declaration fixed the issue.

**Comment by samartha-siddhartha** [comment]
The same is showing when I am using date examples.
Other portals are talking about spinx installation

**Comment by masete** [comment]
for component in layout_value._traverse():  # pylint: disable=protected-access
AttributeError: 'function' object has no attribute '_traverse'
