### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by Llannelongue** [plotly/dash#2064]
Hi, I've just updated to the last version of dash, and now get a cryptic error `Cannot read properties of undefined (reading 'map')` (on chrome) or `y is undefined` (on firefox) (full traceback below). The update is the only change. Any suggestions? :) 

It's probably related to the `go.Choropleth` part of the code as it doesn't display properly. I haven't been able to create a minimal example but full code [here](https://github.com/GreenAlgorithms/green-algorithms-tool/tree/load_old_versions).

Thanks!

I updated from:
```
dash==1.4.1
dash-core-components==1.3.1
dash-html-components==1.0.1
dash-renderer==1.1.2
dash-table==4.4.1
```
to:
```
dash==2.4.1
dash-bootstrap-components==1.1.0
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-renderer==1.1.2
dash-table==5.0.0
```

**EDIT: I've narrowed it down to 2 specific releases of dash:**
- **1.8.0 is when the choropleth map stopped displaying (showing an empty div instead) but with no error message**
- **2.4.0 is when the error message mentioned here appeared**

Full traceback on Chrome:
```
TypeError: Cannot read properties of undefined (reading 'map')

    at http://127.0.0.1:8050/_dash-component-suites/dash/dcc/async-dropdown.js:2:4888

    at commitHookEffectListMount (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_4_1m1653310444.14.0.js:19866:28)

    at commitPassiveHookEffects (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_4_1m1653310444.14.0.js:19904:13)

    at HTMLUnknownElement.callCallback (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_4_1m1653310444.14.0.js:182:16)

    at Object.invokeGuardedCallbackDev (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_4_1m1653310444.14.0.js:231:18)

    at invokeGuardedCallback (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_4_1m1653310444.14.0.js:286:33)

    at flushPassiveEffectsImpl (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_4_1m1653310444.14.0.js:22988:11)

    at unstable_runWithPriority (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react@16.v2_4_1m1653310444.14.0.js:2685:14)

    at runWithPriority$1 (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_4_1m1653310444.14.0.js:11174:12)

    at flushPassiveEffects (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_4_1m1653310444.14.0.js:22955:14)
```

**Comment by zirondi** [comment]
I had a similar issue where I was trying to change a value in a callback that was not properly initialized, see [link](https://community.plotly.com/t/reset-dcc-rangeslider-to-initial-value/64371/3?u=zirondi).

I could not identify it in your code, but I think somewhere you're updating the Y value of some component and it isn't loaded properly yet.

This error message is rather cryptic.
