### ISSUE TITLE
[BUG] typescript complier RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Jordan-Hall** [plotly/dash#2066]
Repo: https://github.com/communitiesuk/gov-uk-dash-react-components/tree/move-to-ts

**Output:**

```
c:\dev\clients\communitiesuk\uk_gov_dash_components\node_modules\typescript\lib\typescript.js:52545
                        return type.flags & 1048576 /* TypeFlags.Union */ ? ts.factory.createUnionTypeNode(typeNodes) : ts.factory.createIntersectionTypeNode(typeNodes);
                                                                                       ^

RangeError: Maximum call stack size exceeded
    at typeToTypeNodeHelper (c:\dev\clients\communitiesuk\uk_gov_dash_components\node_modules\typescript\lib\typescript.js:52545:88)
    at serializeTypeForDeclaration (c:\dev\clients\communitiesuk\uk_gov_dash_components\node_modules\typescript\lib\typescript.js:53892:30)
    at symbolToParameterDeclaration (c:\dev\clients\communitiesuk\uk_gov_dash_components\node_modules\typescript\lib\typescript.js:53321:41)
    at c:\dev\clients\communitiesuk\uk_gov_dash_components\node_modules\typescript\lib\typescript.js:53231:274
    at Array.map (<anonymous>)
    at signatureToSignatureDeclarationHelper (c:\dev\clients\communitiesuk\uk_gov_dash_components\node_modules\typescript\lib\typescript.js:53231:240)
    at createTypeNodesFromResolvedType (c:\dev\clients\communitiesuk\uk_gov_dash_components\node_modules\typescript\lib\typescript.js:52990:43)
    at createTypeNodeFromObjectType (c:\dev\clients\communitiesuk\uk_gov_dash_components\node_modules\typescript\lib\typescript.js:52837:35)
    at visitAndTransformType (c:\dev\clients\communitiesuk\uk_gov_dash_components\node_modules\typescript\lib\typescript.js:52764:34)
    at createAnonymousTypeNode (c:\dev\clients\communitiesuk\uk_gov_dash_components\node_modules\typescript\lib\typescript.js:52702:36)

Error generating metadata in uk_gov_dash_components (status=1)
````

**Comment by Jordan-Hall** [comment]
@T4rk1n  I can take a look soon.  I assume its you that will be dealing with TS complier at plotly

**Comment by T4rk1n** [comment]
@Jordan-Hall I had a look at your repo, in the `Autocomplete`, you have this prop: https://github.com/communitiesuk/gov-uk-dash-react-components/blob/7e31d073aeca2cc5f7eb3b28686bc6c2112cc632/src/ts/components/AutoComplete.tsx#L127

Its the default typescript lib.dom.d.ts `HTMLSelectElement` and that is where the error come, I don't think those are supported as props.

**Comment by alexcjohnson** [comment]
That's an awfully cryptic way to tell you a type is unsupported! If that's indeed the issue, is there any way we can make that friendlier?

**Comment by Jordan-Hall** [comment]
> Its the default typescript lib.dom.d.ts `HTMLSelectElement` and that is where the error come, I don't think those are supported as props.

Tried changing that to any and still getting same issue

**Comment by T4rk1n** [comment]
This error is with nested types when resolving the type of the properties of shapes, the behavior can be reproduced with a nested type like this:

```ts
type Nested = {
    nested: Nested;
}

type Props = {
   nested: Nested;
}
```

 Some types in the dom lib are nested so they bug:

```ts
const NESTED_TYPES = [
    'ChildNode',
    'HTMLElement',
    'ParentNode',
    'HTMLSlotElement',
    'CSSRule'
];
```

Can also add `Document` and `ShadowRoot` to types that incur a nesting in their type tree.

**Comment by Jordan-Hall** [comment]
Aww never mind its a completely different bug. I've found the reason and I know the solutions (I think)  Its because of exporting mutiple things in the file (which I think should be allowed. I'll come up with a solution and create PR
