### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'traverse'

### ISSUE THREAD

**Issue by ahmedsalhin** [plotly/dash#220]
while trying to `app.css.get_all_css()` I get this error

```
Traceback (most recent call last):
  File "/Users/ahmed.salhin/anaconda3/envs/cash_flow/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-94-41ada8291459>", line 1, in <module>
    app.css.get_all_css()
  File "/Users/ahmed.salhin/anaconda3/envs/cash_flow/lib/python3.6/site-packages/dash/resources.py", line 104, in get_all_css
    return self._resources.get_all_resources()
  File "/Users/ahmed.salhin/anaconda3/envs/cash_flow/lib/python3.6/site-packages/dash/resources.py", line 56, in get_all_resources
    all_resources = (
  File "/Users/ahmed.salhin/anaconda3/envs/cash_flow/lib/python3.6/site-packages/dash/resources.py", line 87, in get_inferred_resources
    extract_resource_from_component(t)
AttributeError: 'NoneType' object has no attribute 'traverse'
```

**Comment by ned2** [comment]
This looks like the `layout` attribute has not been set. Check that you have actually assigned a value to the `layout` attribute of your Dash instance. If you have done that somewhere, then it's likely an import order issue, where the app is being run without importing the module that assigns `layout` a value. I actually just suggested a solution to this issue over on #221.
