### ISSUE TITLE
[BUG] can't activate debug mode

### ISSUE THREAD

**Issue by nchesk** [plotly/dash#2240]
python 3.7.4

```
dash                                       2.6.1
dash-bootstrap-components                  1.0.2
dash-core-components                       2.0.0
dash-html-components                       2.0.0
dash-table                                 5.0.0
dash-themes                                0.0.2
```
I’m trying to activate debug mode, but i get this error:
```
Traceback (most recent call last):

  File "C:/Users/nchesk/dev/data_analysis_platform/dapl/app.py", line 80, in <module>
    dev_tools_prune_errors=False)
  File "C:\Anaconda3\lib\site-packages\dash\dash.py", line 2128, in run_server
    self.run(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\dash\dash.py", line 1904, in run
    dev_tools_prune_errors
  File "C:\Anaconda3\lib\site-packages\dash\dash.py", line 1661, in enable_dev_tools
    for package in packages
  File "C:\Anaconda3\lib\site-packages\dash\dash.py", line 1661, in <listcomp>
    for package in packages
TypeError: '_NamespacePath' object is not subscriptable
```
Process finished with exit code 1
When i’m running code without debug=True flag it works fine

here’s my code
```
from dash import page_container, page_registry, dash_table
import dash_bootstrap_components as dbc
from dash_extensions.enrich import ( DashProxy, MultiplexerTransform, html, dcc)
from dash_extensions.enrich import Output, Input, State, callback


app = DashProxy(__name__,
                transforms=[MultiplexerTransform()],
                use_pages=True,
                prevent_initial_callbacks=True,
                suppress_callback_exceptions=True,
                external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container([ dbc.Container(page_container)])

if __name__ == '__main__':
    app.run(debug=True)
```
What should i change in order to make it works?

**Comment by kshitiz305** [comment]
What version of DashProxy is being used as the product is working fine with the latest version of the python and dash

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
