### ISSUE TITLE
Tox tests fail on master branch

### ISSUE THREAD

**Issue by rmarren1** [plotly/dash#236]
With a fresh clone of the master branch, running tox hits an error for both python2.7 and python3.6
Full output:
```
ryan@galliumos:~/MSK/dash/base/dash$ tox
GLOB sdist-make: /home/ryan/MSK/dash/base/dash/setup.py
py27 create: /home/ryan/MSK/dash/base/dash/.tox/py27
py27 installdeps: -rdev-requirements.txt
py27 inst: /home/ryan/MSK/dash/base/dash/.tox/dist/dash-0.21.0.zip
py27 installed: asn1crypto==0.24.0,astroid==1.6.2,backports.functools-lru-cache==1.5,certifi==2018.1.18,cffi==1.11.5,chardet==3.0.4,click==6.7,configparser==3.5.0,cryptography==2.2.2,dash==0.21.0,dash-core-components==0.21.1,dash-flow-example==0.0.3,dash-html-components==0.9.0,dash-renderer==0.12.1,decorator==4.2.1,enum34==1.1.6,flake8==3.5.0,Flask==0.12.2,Flask-Compress==1.4.0,funcsigs==1.0.2,functools32==3.2.3.post2,futures==3.2.0,idna==2.6,ipaddress==1.0.19,ipython-genutils==0.2.0,isort==4.3.4,itsdangerous==0.24,Jinja2==2.10,jsonschema==2.6.0,jupyter-core==4.4.0,lazy-object-proxy==1.3.1,MarkupSafe==1.0,mccabe==0.6.1,mock==2.0.0,nbformat==4.4.0,pbr==4.0.0,percy==1.1.0,plotly==2.5.1,pluggy==0.6.0,py==1.5.3,pycodestyle==2.3.1,pycparser==2.18,pyflakes==1.6.0,pylint==1.8.3,pyOpenSSL==17.5.0,pytz==2018.3,requests==2.18.4,selenium==3.11.0,singledispatch==3.4.0.3,six==1.11.0,tox==2.9.1,tox-pyenv==1.1.0,traitlets==4.3.2,urllib3==1.22,virtualenv==15.2.0,Werkzeug==0.14.1,wrapt==1.10.11
py27 runtests: PYTHONHASHSEED='486919446'
py27 runtests: commands[0] | python --version
Python 2.7.12
py27 runtests: commands[1] | python -m unittest tests.test_integration
 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Mar/2018 20:43:48] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:43:48] "GET /_dash-component-suites/dash_renderer/react@15.4.2.min.js?v=0.12.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:43:48] "GET /_dash-component-suites/dash_renderer/react-dom@15.4.2.min.js?v=0.12.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:43:48] "GET /_dash-component-suites/dash_core_components/plotly-1.35.2.min.js?v=0.21.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:43:48] "GET /_dash-component-suites/dash_html_components/bundle.js?v=0.9.0 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:43:48] "GET /_dash-component-suites/dash_core_components/bundle.js?v=0.21.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:43:48] "GET /_dash-component-suites/dash_renderer/bundle.js?v=0.12.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:43:50] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:43:50] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:43:50] "GET /favicon.ico HTTP/1.1" 200 -
testing callback does not update
127.0.0.1 - - [29/Mar/2018 20:43:50] "POST /_dash-update-component HTTP/1.1" 204 -
testing callback does not update
127.0.0.1 - - [29/Mar/2018 20:43:51] "POST /_dash-update-component HTTP/1.1" 204 -
aborted - sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
. * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Mar/2018 20:43:56] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:43:56] "GET /_dash-component-suites/dash_renderer/react-dom@15.4.2.min.js?v=0.12.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:43:56] "GET /_dash-component-suites/dash_renderer/react@15.4.2.min.js?v=0.12.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:43:56] "GET /_dash-component-suites/dash_flow_example/bundle.js?v=0.0.3 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:43:56] "GET /_dash-component-suites/dash_html_components/bundle.js?v=0.9.0 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:43:56] "GET /_dash-component-suites/dash_renderer/bundle.js?v=0.12.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:43:57] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:43:57] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:43:57] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:43:57] "POST /_dash-update-component HTTP/1.1" 200 -
flowtype - sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
. * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Mar/2018 20:44:02] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:02] "GET /_dash-component-suites/dash_core_components/plotly-1.35.2.min.js?v=0.21.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:02] "GET /_dash-component-suites/dash_html_components/bundle.js?v=0.9.0 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:02] "GET /_dash-component-suites/dash_renderer/react@15.4.2.min.js?v=0.12.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:02] "GET /_dash-component-suites/dash_renderer/react-dom@15.4.2.min.js?v=0.12.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:02] "GET /_dash-component-suites/dash_core_components/bundle.js?v=0.21.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:02] "GET /_dash-component-suites/dash_renderer/bundle.js?v=0.12.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:04] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:04] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:04] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:04] "POST /_dash-update-component HTTP/1.1" 200 -
simple-callback-1 - sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
127.0.0.1 - - [29/Mar/2018 20:44:05] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:05] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:05] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:05] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:05] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:05] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:05] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:05] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:05] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:05] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:44:05] "POST /_dash-update-component HTTP/1.1" 200 -
simple-callback-2 - sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
.
----------------------------------------------------------------------
Ran 3 tests in 24.591s

OK
py27 runtests: commands[2] | python -m unittest tests.test_react
ssss.ssss..E.....
======================================================================
ERROR: test_exception_event_not_in_component (tests.test_react.TestCallbacks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_react.py", line 436, in test_exception_event_not_in_component
    events=[Event(id, 'click')]
  File "dash/dash.py", line 489, in callback
    self._validate_callback(output, inputs, state, events)
  File "dash/dash.py", line 440, in _validate_callback
    component.available_events).replace('    ', ''))
NonExistantEventException: 
Attempting to assign a callback with
the event "click" but the component
"output" doesn't have "click" as an event.

Here is a list of the available events in "output":
[]


----------------------------------------------------------------------
Ran 17 tests in 0.053s

FAILED (errors=1, skipped=8)
ERROR: InvocationError: '/home/ryan/MSK/dash/base/dash/.tox/py27/bin/python -m unittest tests.test_react'
py36 create: /home/ryan/MSK/dash/base/dash/.tox/py36
py36 installdeps: -rdev-requirements.txt
py36 inst: /home/ryan/MSK/dash/base/dash/.tox/dist/dash-0.21.0.zip
py36 installed: asn1crypto==0.24.0,astroid==1.6.2,certifi==2018.1.18,cffi==1.11.5,chardet==3.0.4,click==6.7,cryptography==2.2.2,dash==0.21.0,dash-core-components==0.21.1,dash-flow-example==0.0.3,dash-html-components==0.9.0,dash-renderer==0.12.1,decorator==4.2.1,flake8==3.5.0,Flask==0.12.2,Flask-Compress==1.4.0,idna==2.6,ipython-genutils==0.2.0,isort==4.3.4,itsdangerous==0.24,Jinja2==2.10,jsonschema==2.6.0,jupyter-core==4.4.0,lazy-object-proxy==1.3.1,MarkupSafe==1.0,mccabe==0.6.1,mock==2.0.0,nbformat==4.4.0,pbr==4.0.0,percy==1.1.0,plotly==2.5.1,pluggy==0.6.0,py==1.5.3,pycodestyle==2.3.1,pycparser==2.18,pyflakes==1.6.0,pylint==1.8.3,pyOpenSSL==17.5.0,pytz==2018.3,requests==2.18.4,selenium==3.11.0,six==1.11.0,tox==2.9.1,tox-pyenv==1.1.0,traitlets==4.3.2,urllib3==1.22,virtualenv==15.2.0,Werkzeug==0.14.1,wrapt==1.10.11
py36 runtests: PYTHONHASHSEED='486919446'
py36 runtests: commands[0] | python --version
Python 3.6.5
py36 runtests: commands[1] | python -m unittest tests.test_integration
 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Mar/2018 20:45:12] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:12] "GET /_dash-component-suites/dash_renderer/react-dom@15.4.2.min.js?v=0.12.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:12] "GET /_dash-component-suites/dash_html_components/bundle.js?v=0.9.0 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:12] "GET /_dash-component-suites/dash_renderer/react@15.4.2.min.js?v=0.12.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:12] "GET /_dash-component-suites/dash_core_components/bundle.js?v=0.21.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:12] "GET /_dash-component-suites/dash_renderer/bundle.js?v=0.12.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:12] "GET /_dash-component-suites/dash_core_components/plotly-1.35.2.min.js?v=0.21.1 HTTP/1.1" 200 -
/home/ryan/MSK/dash/base/dash/.tox/py36/lib/python3.6/site-packages/werkzeug/local.py:347: DeprecationWarning:

Request.is_xhr is deprecated. Given that the X-Requested-With header is not a part of any spec, it is not reliable

127.0.0.1 - - [29/Mar/2018 20:45:15] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:15] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:15] "GET /favicon.ico HTTP/1.1" 200 -
testing callback does not update
127.0.0.1 - - [29/Mar/2018 20:45:15] "POST /_dash-update-component HTTP/1.1" 204 -
testing callback does not update
127.0.0.1 - - [29/Mar/2018 20:45:16] "POST /_dash-update-component HTTP/1.1" 204 -
aborted - sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
. * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Mar/2018 20:45:21] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:21] "GET /_dash-component-suites/dash_renderer/react@15.4.2.min.js?v=0.12.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:21] "GET /_dash-component-suites/dash_renderer/react-dom@15.4.2.min.js?v=0.12.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:21] "GET /_dash-component-suites/dash_html_components/bundle.js?v=0.9.0 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:21] "GET /_dash-component-suites/dash_flow_example/bundle.js?v=0.0.3 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:21] "GET /_dash-component-suites/dash_renderer/bundle.js?v=0.12.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:21] "GET /_dash-layout HTTP/1.1" 200 -
/home/ryan/MSK/dash/base/dash/.tox/py36/lib/python3.6/site-packages/werkzeug/local.py:347: DeprecationWarning:

Request.is_xhr is deprecated. Given that the X-Requested-With header is not a part of any spec, it is not reliable

127.0.0.1 - - [29/Mar/2018 20:45:21] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:21] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:21] "POST /_dash-update-component HTTP/1.1" 200 -
flowtype - sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
. * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Mar/2018 20:45:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:26] "GET /_dash-component-suites/dash_html_components/bundle.js?v=0.9.0 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:26] "GET /_dash-component-suites/dash_renderer/react-dom@15.4.2.min.js?v=0.12.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:26] "GET /_dash-component-suites/dash_renderer/react@15.4.2.min.js?v=0.12.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:26] "GET /_dash-component-suites/dash_core_components/plotly-1.35.2.min.js?v=0.21.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:26] "GET /_dash-component-suites/dash_core_components/bundle.js?v=0.21.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:26] "GET /_dash-component-suites/dash_renderer/bundle.js?v=0.12.1 HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:28] "GET /_dash-layout HTTP/1.1" 200 -
/home/ryan/MSK/dash/base/dash/.tox/py36/lib/python3.6/site-packages/werkzeug/local.py:347: DeprecationWarning:

Request.is_xhr is deprecated. Given that the X-Requested-With header is not a part of any spec, it is not reliable

127.0.0.1 - - [29/Mar/2018 20:45:28] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:28] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:28] "POST /_dash-update-component HTTP/1.1" 200 -
simple-callback-1 - sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
127.0.0.1 - - [29/Mar/2018 20:45:29] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:29] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:29] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:29] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:29] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:29] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:29] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:29] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:29] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:29] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 20:45:29] "POST /_dash-update-component HTTP/1.1" 200 -
simple-callback-2 - sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
.
----------------------------------------------------------------------
Ran 3 tests in 25.880s

OK
py36 runtests: commands[2] | python -m unittest tests.test_react
ssss.ssss..E.....
======================================================================
ERROR: test_exception_event_not_in_component (tests.test_react.TestCallbacks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ryan/MSK/dash/base/dash/tests/test_react.py", line 436, in test_exception_event_not_in_component
    events=[Event(id, 'click')]
  File "/home/ryan/MSK/dash/base/dash/dash/dash.py", line 489, in callback
    self._validate_callback(output, inputs, state, events)
  File "/home/ryan/MSK/dash/base/dash/dash/dash.py", line 440, in _validate_callback
    component.available_events).replace('    ', ''))
dash.exceptions.NonExistantEventException: 
Attempting to assign a callback with
the event "click" but the component
"output" doesn't have "click" as an event.

Here is a list of the available events in "output":
[]


----------------------------------------------------------------------
Ran 17 tests in 0.056s

FAILED (errors=1, skipped=8)
ERROR: InvocationError: '/home/ryan/MSK/dash/base/dash/.tox/py36/bin/python -m unittest tests.test_react'
_______________________________________________ summary ________________________________________________
ERROR:   py27: commands failed
ERROR:   py36: commands failed
ryan@galliumos:~/MSK/dash/base/dash$
```

**Comment by ned2** [comment]
Yep, I've reported the underlying cause of this problem here: #232.

**Comment by rmarren1** [comment]
This doesn't happen anymore.
