### ISSUE TITLE
[BUG] Patch is not working when registering the callback without decorator

### ISSUE THREAD

**Issue by jfehre** [plotly/dash#2485]
**Describe your context**
```
dash                      2.9.2
dash-bootstrap-components 0.13.0
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-table                5.0.0
```

**Describe the bug**

When adding a patch callback with `app.callback()` following error is thrown:
```
[2023-03-30 23:22:18,426] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/home/jonas/anaconda3/envs/dashboard/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jonas/anaconda3/envs/dashboard/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jonas/anaconda3/envs/dashboard/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jonas/anaconda3/envs/dashboard/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jonas/anaconda3/envs/dashboard/lib/python3.8/site-packages/dash/dash.py", line 1283, in dispatch
    ctx.run(
  File "/home/jonas/anaconda3/envs/dashboard/lib/python3.8/site-packages/dash/_callback.py", line 465, in add_context
    flat_output_values = flatten_grouping(output_value, output)
  File "/home/jonas/anaconda3/envs/dashboard/lib/python3.8/site-packages/dash/_grouping.py", line 35, in flatten_grouping
    validate_grouping(grouping, schema)
  File "/home/jonas/anaconda3/envs/dashboard/lib/python3.8/site-packages/dash/_grouping.py", line 210, in validate_grouping
    SchemaTypeValidationError.check(grouping, full_schema, path, (tuple, list))
  File "/home/jonas/anaconda3/envs/dashboard/lib/python3.8/site-packages/dash/_grouping.py", line 162, in check
    raise SchemaTypeValidationError(value, full_schema, path, expected_type)
dash._grouping.SchemaTypeValidationError: Schema: [<Output `page.children`>]
Path: ()
Expected type: (<class 'tuple'>, <class 'list'>)
Received value of type <class 'dash._patch.Patch'>:
    <dash._patch.Patch object at 0x7f33dfad8b80>
127.0.0.1 - - [30/Mar/2023 23:22:18] "POST /_dash-update-component HTTP/1.1" 500 -

```

Here is a minimal full app example:
```python
from dash import Dash, Output, Input, Patch, html

app = Dash(__name__)

app.layout = html.Div(id="page", children=
    [
        html.Div("Initial div")
    ]
)


def patch_children(id):
    p = Patch()
    p.append(html.Div("Patched Div"))
    return p


app.callback([Output("page", "children"), Input("page", "n_clicks")])(patch_children)


app.run_server()
```

**Expected behavior**

There should be no error and it should behave like adding the callback with a decorator (e.x. `@app.callback()` or `@dash.callback()`).
Another minimal full app example where the callback is registered with a decorator and working as expected:
```python
from dash import Dash, Output, Input, Patch, html

app = Dash(__name__)

app.layout = html.Div(id="page", children=
    [
        html.Div("Initial div")
    ]
)

@app.callback(
    Output("page", "children"),
    Input("page", "n_clicks")
)
def patch_children(id):
    p = Patch()
    p.append(html.Div("Patched Div"))
    return p


app.run_server()
```

Patching functionality was added with PR #2414.
@T4rk1n maybe you have an idea?

**Comment by T4rk1n** [comment]
> app.callback([Output("page", "children"), Input("page", "n_clicks")])(patch_children)

You have both `Output`/`Input` inside the same list, it think it's a multi output, remove the `[]`.

**Comment by jfehre** [comment]
Oh my bad... thanks a lot for your fast clarification.
Now everything works as expected.
