### ISSUE TITLE
Importing keras results in exception dash server crash

### ISSUE THREAD

**Issue by IgorTelezhinsky** [plotly/dash#249]
Dear plotly, I've just started using dash and want to thank for the great library! It looks however that there is a bug: dash server crashes after keras import if run in ipython console of Spyder. If run from the console via python dash_server.py, the keras import does not crash the app. I use anaconda python 3.6.3 on windows 7, keras-gpu (installed via conda) and tensorflow backend.  Note that tensorflow import alone does not affect the app.
dash.\_\_version\_\_
'0.21.0'
keras.\_\_version\_\_
'2.1.5' 

Code to reproduce the error:
import dash
import dash_core_components as dcc
import dash_html_components as html

import keras 

app = dash.Dash()

app.layout = html.Div(children=[
    html.H1(children='Dash Tutorials'),
    dcc.Graph(
        id='example',
        figure=
        {
            'data':
            [
                {'x': [1, 2, 3, 4, 5], 'y': [9, 6, 2, 1, 5], 'type': 'line', 'name': 'Boats'},
                {'x': [1, 2, 3, 4, 5], 'y': [8, 7, 2, 7, 3], 'type': 'bar', 'name': 'Cars'},
            ],
            'layout':
            {
                'title': 'Basic Dash Example'
            }
        }
    )]
)

if \_\_name\_\_ == '\_\_main\_\_':
    app.run_server(debug=True)

**Comment by chriddyp** [comment]
And this doesn't crash if you don't include `import keras`? Maybe this is actually an issue with `keras`? I'm not sure if this is actually an issue with Dash vs Keras vs the underlying server that Dash uses, Flask.

Is there any more information that you can provide?

**Comment by IgorTelezhinsky** [comment]
Hi Chris,

sorry for the delayed response. Here, I hope, is a reproducible example.

1. If I run dash_example.py (see attached zip) from within Spyder iPython console or Anaconda command line (CL) with the command: "python dash_example.py" it runs fine.
2. If I uncomment "import keras" and run it within Spyder, it crashes:

Traceback (most recent call last):

  File "<ipython-input-1-94e74d45a2a7>", line 1, in <module>
    runfile('C:/Users/Me/dash_example.py', wdir='C:/Users/Me')

  File "C:\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Me/dash_example.py", line 30, in <module>
    app.run_server(debug=True)

  File "C:\anaconda3\envs\tf-py36-gpu\lib\site-packages\dash\dash.py", line 566, in run_server
    self.server.run(port=port, debug=debug, **flask_run_options)

  File "C:\anaconda3\lib\site-packages\flask\app.py", line 841, in run
    run_simple(host, port, self, **options)

  File "C:\anaconda3\lib\site-packages\werkzeug\serving.py", line 737, in run_simple
    reloader_type)

  File "C:\anaconda3\lib\site-packages\werkzeug\_reloader.py", line 265, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())

3. If I uncomment "import keras", but run it in Anaconda CL it runs fine

Moreover, there is absolutely opposite behaviour with matplotlib:
2a. If I uncomment "import matplotlib.pyplot as plt" and run it within Spyder, it runs fine.
3a. If I uncomment "import matplotlib.pyplot as plt", but run it in Anaconda CL, it crashes.

I attach my env packages in crash_env_package_list.txt and crash_env_pip_freeze.txt. I installed Anaconda with Anaconda3-5.0.1-Windows-x86_64.exe. What else could I provide?

Cheers,
Igor

[crash_env_package_list.txt](https://github.com/plotly/dash/files/1974267/crash_env_package_list.txt)
[crash_env_pip_freeze.txt](https://github.com/plotly/dash/files/1974265/crash_env_pip_freeze.txt)
[dash_example.zip](https://github.com/plotly/dash/files/1974243/dash_example.zip)

**Comment by chriddyp** [comment]
What if you set `debug=False`?

**Comment by guillaumebugnonNV** [comment]
Hi,
I get the same error:
`sys.exit(reloader.restart_with_reloader())` since I updated flask to the last release with a new clean env.

With `debug=False`, I did not have the issue.

Thanks

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
