### ISSUE TITLE
[BUG] Creating two different scatter_mapbox, one often fails

### ISSUE THREAD

**Issue by jontis** [plotly/dash#2495]
I create two different scatter_mapbox with similar data.

Sample:
 ```
div_mapbox = html.Div([dcc.Graph(figure=figure, id='figmapbox', style={'width': '90vw', 'height': '90vh'})],
                          id = 'divmapbox',
                          style={'width': '90%', 'display': 'inline-block', 'height': '90%', 'position': 'absolute', 'z-index': '1'}
                          )
```

With figure either:
```
def get_fig_openseamap(wpts):
    fig = px.scatter_mapbox(data_frame=wpts, lat="lat", lon="lon", size='size_marker', size_max=8, opacity=1.0, hover_data={'size_marker': False, 'lat':False, 'lon': False, 'energy': True, 'dist': True, 'eta': True})
    fig2 = px.line_mapbox(data_frame=wpts, lat="lat", lon="lon")
    fig.add_trace(fig2.data[0])
    fig.update_layout(mapbox_style="open-street-map")
    fig.update_layout(mapbox_layers=[source_openseamap])
    fig.update({'layout':{'autosize':True,
                          'margin': {"t": 5,"b": 5,"l": 5,"r": 5}}})
    return fig
```

Or:

```
def get_fig_northstar(wpts):
    fig = px.line_mapbox(data_frame=wpts, lat="lat", lon="lon")
    fig2 = px.scatter_mapbox(data_frame=wpts.query('ghost == 0'), lat="lat", lon="lon", opacity=1, hover_data={'lat': False, 'lon': False, 'energy': True, 'dist': True, 'eta': True})
    fig.add_trace(fig2.data[0])
    fig.update_layout(mapbox_style=mapbox_style_northstar)
    fig.update({'layout':{'autosize':True,
                          'margin': {"t": 5,"b": 5,"l": 5,"r": 5}}})
    return fig
```

Where openseamap layer is the openseamap marks tile.
Nothstar is the official mapbox style northstar, that needs to be copied into a personal account to work.

I can run each of them on its own, no problems. Sometimes, running both works, and sometimes it fails. 
The failure normally appears like one map working perfect, the other has no graphics, BUT the hoverlayer works, so hovering over a point (that cant be seen) shows the hover data.

It seems a bit stochastic to me. 
I can also replace the figure with callbacks using Output('figmapbox', 'figure')
As long as it's one at a time, it works fine. Having both can work but normally not.
Any suggestions how to debug this? I have suspected race conditions and tried delaying creating one of them but saw no improvement.

dash                                       2.8.1
dash-core-components      2.0.0 
dash-daq                               0.5.0 
dash-html-components      2.0.0

OS: pop_os 22.04 (ubuntu 22.04)
Chrome 110.0.5481.96 (Official Build) (64-bit)

**Comment by jontis** [comment]
Screenshot where top map (northstar failed)
![image](https://user-images.githubusercontent.com/1307210/229776187-295843e3-5a3d-46bf-a2ea-17ceb21243e6.png)

**Comment by jontis** [comment]
Screenshot where lower map (openseamap) failed.
![image](https://user-images.githubusercontent.com/1307210/229777821-dfab871d-bb60-4fbf-ad1e-013f55302510.png)

**Comment by jontis** [comment]
Only difference between those runs is that I delayed creating the lower one second. If both are created at the same time, northstar fails. If openseamap is delayed, that fails, but northstar succed. At rare occasions, it seems both succed, but it's rare.

Now also tried with:
dash     2.9.2

Same problem.

**Comment by jontis** [comment]
Same behavior with:
Firefox
dash 2.5
dash 2.6

**Comment by jontis** [comment]
Found one workaround.
If i update top figure with Output(..., 'figure') and update the lower one by replacing the dcc.Graph(figure=figure) in the div, they both come alive.
I have no idea why.

![image](https://user-images.githubusercontent.com/1307210/229782532-415e48ae-c882-44a9-8c55-aafda7f2b120.png)

**Comment by alexcjohnson** [comment]
Thanks @jontis - your screenshot shows that there's an error, is that related to this? Maybe not, because it's there even in the case that worked, but maybe yes, what does the error message say?

**Comment by jontis** [comment]
No, the error was related to something else. The error is corrected now, and the maps behavior is the same. It seems that if I provoke them to both load tiles at the same time, often at least one will stop loading tiles and never start again.

**Comment by jontis** [comment]
Some of these errors turned up in chrome developers view:
78async-plotlyjs.js:1 Uncaught Error: An API access token is required to use Mapbox GL. See https://www.mapbox.com/api-documentation/#access-tokens-and-token-scopes
    at q._makeAPIURL (async-plotlyjs.js:1:2464255)
    at q.normalizeTileURL (async-plotlyjs.js:1:2463465)
    at r.loadTile (async-plotlyjs.js:1:2863541)
    at r._loadTile (async-plotlyjs.js:1:2907343)
    at r._addTile (async-plotlyjs.js:1:2915220)
    at r._updateRetainedTiles (async-plotlyjs.js:1:2913725)
    at r.update (async-plotlyjs.js:1:2912672)
    at r._updateSources (async-plotlyjs.js:1:2979510)
    at i._render (async-plotlyjs.js:1:3173689)
    at async-plotlyjs.js:1:3175965

Interesting, as it new it's access token when they were instantiated. Did it forget, or did communication fail.

**Comment by nickmelnikov82** [comment]
Hello! Thank you! 
The issue you describe seems quite complex and could have several potential causes:

Check your Mapbox access tokens: The error you are seeing in the developer console indicates that the required Mapbox access token was not provided or was provided incorrectly. Make sure you have a valid Mapbox access token and verify that it is being used correctly in your code.

Update the versions of the Dash libraries: Please note that you are using older versions of Dash libraries (2.8.1, 2.0.0, etc.). Try updating these libraries to the latest version and see if that solves the problem. The update may contain bug fixes that could affect the way your code works.

Also add the error code to better understand what is going wrong.
The solution to your problem is described [here](https://github.com/alex3165/react-mapbox-gl/issues/822)
