### ISSUE TITLE
dash_renderer missing after pip install dash

### ISSUE THREAD

**Issue by gavinB-orange** [plotly/dash#27]
I created a virtualenv, then did pip install dash. This worked fine 
```
:
:
Successfully built dash flask-compress flask-seasurf plotly
Installing collected packages: itsdangerous, click, Werkzeug, MarkupSafe, Jinja2, Flask, flask-compress, flask-seasurf, decorator, enum34, six, ipython-genutils, traitlets, jupyter-core, functools32, jsonschema, nbformat, pytz, idna, urllib3, chardet, certifi, requests, plotly, dash
Successfully installed Flask-0.12.2 Jinja2-2.9.6 MarkupSafe-1.0 Werkzeug-0.12.2 certifi-2017.4.17 chardet-3.0.4 click-6.7 dash-0.17.5 decorator-4.0.11 enum34-1.1.6 flask-compress-1.4.0 flask-seasurf-0.2.2 functools32-3.2.3.post2 idna-2.5 ipython-genutils-0.2.0 itsdangerous-0.24 jsonschema-2.6.0 jupyter-core-4.3.0 nbformat-4.3.0 plotly-2.0.11 pytz-2017.2 requests-2.18.1 six-1.10.0 traitlets-4.3.2 urllib3-1.21.1
```

However 

```
(venv) gavin@gbws ~/work/uncle/graphs/plotly_dash $ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from dash.react import Dash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gavin/work/uncle/graphs/plotly_dash/venv/local/lib/python2.7/site-packages/dash/__init__.py", line 1, in <module>
    from .dash import Dash
  File "/home/gavin/work/uncle/graphs/plotly_dash/venv/local/lib/python2.7/site-packages/dash/dash.py", line 15, in <module>
    import dash_renderer
ImportError: No module named dash_renderer
```

Fixed by pip install dash_renderer, but should dash_renderer not be added as a dependency?

**Comment by gavinB-orange** [comment]
OK - I was led astray by the "just pip install dash to install" comments.
