### ISSUE TITLE
[BUG] OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

### ISSUE THREAD

**Issue by leo-smi** [plotly/dash#2792]
Code:

```
import dash
from dash import Dash, html, dcc


app = Dash(__name__, use_pages=True)


app.layout = html.Div([
    html.H1('Multi-page app with Dash Pages'),
    html.Div([
        html.Div(
            dcc.Link(f"{page['name']} - {page['path']}", href=page["relative_path"])
        ) for page in dash.page_registry.values()
    ]),
    dash.page_container
])


if __name__ == '__main__':
    app.run(debug=True)
```

**Describe your context**

```
python 3.11
dash                 2.16.1
dash-core-components 2.0.0
dash-html-components 2.0.0
dash-table           5.0.0
```

Browser

    - OS: windows 10
    - Browser: Edge 122.0.2365.80

**Describe the bug**

```
Dash is running on http://127.0.0.1:8050/

 * Serving Flask app 'main'
 * Debug mode: on
Traceback (most recent call last):
  File "C:\Users\leand\AppData\Roaming\PyScripter\remserver.py", line 95, in <module>
    main()
  File "C:\Users\leand\AppData\Roaming\PyScripter\remserver.py", line 91, in main
    t = SimpleServer(ModSlaveService, port = port, auto_register = False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\PyScripter\Lib\rpyc.zip\rpyc\utils\server.py", line 89, in __init__
OSError: [WinError 10048] Normalmente é permitida apenas uma utilização de cada endereço de soquete (protocolo/endereço de rede/porta)
Exit code:  1
```

**Expected behavior**

```
Dash is running on http://127.0.0.1:8050/

 * Serving Flask app 'main'
 * Debug mode: on
```

It's working with python 3.10

**Comment by Coding-with-Adam** [comment]
hi @leo-smi 
Unfortunately, I can't replicate this error with your code. Maybe it's because I am using Windows 11?

Do you think this is related to Windows version or somethign else?

**Comment by leo-smi** [comment]
I updated to windows 11 today ans the error persists

**Comment by leo-smi** [comment]
I'll try creating a new python environment.

**Comment by leo-smi** [comment]
I have update python to 3.12.2, updated dash and the error persists:

```
dash                 2.16.1
dash-core-components 2.0.0
dash-html-components 2.0.0
dash-table           5.0.0
Flask                3.0.2
```

```
Dash is running on http://127.0.0.1:5001/

 * Serving Flask app 'main'
 * Debug mode: on
Traceback (most recent call last):
  File "C:\Users\leand\AppData\Roaming\PyScripter\remserver.py", line 95, in <module>
    main()
  File "C:\Users\leand\AppData\Roaming\PyScripter\remserver.py", line 91, in main
    t = SimpleServer(ModSlaveService, port = port, auto_register = False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\PyScripter\Lib\rpyc.zip\rpyc\utils\server.py", line 89, in __init__
OSError: [WinError 10048] Normalmente é permitida apenas uma utilização de cada endereço de soquete (protocolo/endereço de rede/porta)
Exit code:  1
```

I tried another ports, and nothing happens.

**Comment by leo-smi** [comment]
I did it.

Actually is from the IDE the problem, I swichted from pyscripter to vscodium and is working fine. 

![image](https://github.com/plotly/dash/assets/20663547/4faaf3ca-ed94-4a0f-84b7-13188b857359)
