### ISSUE TITLE
[BUG] Error generating typescript components

### ISSUE THREAD

**Issue by tsveti22** [plotly/dash#2886]
All of a sudden, I started seeing the following error while generating typescript components:

```
I:\ds\projects\dash-salt\node_modules\typescript\lib\typescript.js:50379
            if (symbol.flags & 33554432 /* SymbolFlags.Transient */)
                       ^

TypeError: Cannot read properties of undefined (reading 'flags')
    at getSymbolLinks (I:\projects\node_modules\typescript\lib\typescript.js:50379:24)
    at getExportsOfModule (I:\projects\node_modules\typescript\lib\typescript.js:52656:25)
    at Object.getExportsOfModuleAsArray [as getExportsOfModule] (I:\projects\node_modules\typescript\lib\typescript.js:52595:35)
    at C:\python3.11\site-packages\dash\extract-meta.js:652:33
    at Array.forEach (<anonymous>)
    at gatherComponents (C:\python3.11\site-packages\dash\extract-meta.js:649:33)
    at C:\python3.11\site-packages\dash\extract-meta.js:176:21
    at Array.forEach (<anonymous>)
    at C:\\python3.11\site-packages\dash\extract-meta.js:173:40
    at Array.forEach (<anonymous>)

Node.js v18.20.2

Error generating metadata in dash_salt (status=1)
```

**Describe your context**
I have the following dependencies:
[tool.poetry.dependencies]
python = "^3.11"
wheel = "^0.43.0"
build = "^1.2.1"
dash = {extras = ["dev"], version = "^2.17.1"}
plotly = "^5.22.0"

This is happening on Windows.

Note that the generation script was previously working fine. In fact, this very component was previously built successfully, and we haven't changed it since then. The error first appeared during building a different component. We removed it, and it started showing up for this component, even though we hadn't changed it. I suspect it's something with the environment, but not sure.

**Comment by tsveti22** [comment]
Solved:
I'm not sure if this is what solved it, but in my components folder, I had created an empty tsx file. Once I deleted it, I was able to build again.
