### ISSUE TITLE
[BUG] No module named _plotly_utils

### ISSUE THREAD

**Issue by tsveti22** [plotly/dash#2887]
I am using the typescript template to generate dash components and getting the following error when I run npm run build:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\projects\dash-salt\.venv\Scripts\dash-generate-components.exe\__main__.py", line 4, in <module>
  File "I:\dash-salt\.venv\Lib\site-packages\dash\__init__.py", line 22, in <module>
    from ._callback import callback, clientside_callback  # noqa: F401,E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\projects\dash-salt\.venv\Lib\site-packages\dash\_callback.py", line 34, in <module>
    from .long_callback.managers import BaseLongCallbackManager
  File "I:\projects\dash-salt\.venv\Lib\site-packages\dash\long_callback\__init__.py", line 1, in <module>
    from .managers.celery_manager import (  # noqa: F401,E402
  File "I:\projects\dash-salt\.venv\Lib\site-packages\dash\long_callback\managers\celery_manager.py", line 5, in <module>
    from _plotly_utils.utils import PlotlyJSONEncoder
ModuleNotFoundError: No module named '_plotly_utils'
```

-  replace the result of `pip list | grep dash` below
```
$ poetry show
Warning: Found deprecated priority 'default' for source 'jpmc-internal' in pyproject.toml. You can achieve the same effect by changing the priority to 'primary' and putting the source first.
ansi2html            1.9.1    Convert text with ANSI color codes to HTML or to LaTeX
blinker              1.8.2    Fast, simple object-to-object and broadcast signaling
build                1.2.1    A simple, correct Python build frontend
certifi              2024.6.2 Python package for providing Mozilla's CA Bundle.
charset-normalizer   3.3.2    The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
click                8.1.7    Composable command line interface toolkit
colorama             0.4.6    Cross-platform colored terminal text.
coverage             7.5.3    Code coverage measurement for Python
dash                 2.14.1   A Python framework for building reactive web-apps. Developed by Plotly.
dash-core-components 2.0.0    Core component suite for Dash
dash-html-components 2.0.0    Vanilla HTML components for Dash
dash-table           5.0.0    Dash table
flask                3.0.3    A simple framework for building complex web applications.
idna                 3.7      Internationalized Domain Names in Applications (IDNA)
importlib-metadata   7.1.0    Read metadata from Python packages
iniconfig            2.0.0    brain-dead simple config-ini parsing
itsdangerous         2.2.0    Safely pass data to untrusted environments and back.
jinja2               3.1.4    A very fast and expressive template engine.
markupsafe           2.1.5    Safely add untrusted strings to HTML/XML markup.
nest-asyncio         1.6.0    Patch asyncio to allow nested event loops
packaging            24.1     Core utilities for Python packages
plotly               5.22.0   An open-source, interactive data visualization library for Python
pluggy               1.5.0    plugin and hook calling mechanisms for python
pyproject-hooks      1.1.0    Wrappers to call pyproject.toml-based build backend hooks.
pytest               8.2.2    pytest: simple powerful testing with Python
pytest-cov           5.0.0    Pytest plugin for measuring coverage.
requests             2.32.3   Python HTTP for Humans.
retrying             1.3.4    Retrying
setuptools           70.0.0   Easily download, build, install, upgrade, and uninstall Python packages
six                  1.16.0   Python 2 and 3 compatibility utilities
tenacity             8.3.0    Retry code until it succeeds
typing-extensions    4.12.2   Backported and Experimental Type Hints for Python 3.8+
urllib3              2.2.1    HTTP library with thread-safe connection pooling, file post, and more.
werkzeug             3.0.3    The comprehensive WSGI web application library.
wheel                0.43.0   A built-package format for Python
zipp                 3.19.2   Backport of pathlib-compatible object wrapper for zip files
```
This is running on Windows with Python 3.11.9.

When I run this outside of the poetry virtual environment, it runs fine, but I have the same pip package versions.

**Expected behavior**

Expecting npm run build to build successfully in my virtual environment.

**Comment by tsveti22** [comment]
Solved. 
For some reason poetry had installed plotly as "lotly" and "_plotly_utils" as "~plotly_utils". I deleted my venv, cleared the poetry chache, ran poetry install, and it works
