### ISSUE TITLE
[BUG] Possible Regression with Duplicate Callback Outputs

### ISSUE THREAD

**Issue by RobertJN64** [plotly/dash#2934]
**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                        2.17.1
dash-bootstrap-components   1.6.0
dash-core-components        2.0.0
dash-html-components        2.0.0
dash-table                  5.0.0
```
Bug only appears when running on Google App Engine using gunicorn (and possible when multiple instances active).

**Describe the bug**

Error messages appear in the log indicating that a callback can't be found.
The exact error is:

```
KeyError: "Callback function not found for output '..taxi-client-geo-location.update_now...taxi-client-message-alert.children...taxi-client-message-alert.is_open...taxi-client-message-alert.color...taxi-client-ping-pkid-store.data@0ff8f2f02059be5962c2a13a011d56b1..', perhaps you forgot to prepend the '@'?"
--
raise KeyError(msg) from missing_callback_function
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/dash/dash.py", line 1368, in dispatch
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
^^^^^^^^^^^^^^^^^^^^^^^
rv = self.dispatch_request()
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rv = self.handle_user_exception(e)
File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app    response = self.full_dispatch_request()
The above exception was the direct cause of the following exception:
KeyError: '..taxi-client-geo-location.update_now...taxi-client-message-alert.children...taxi-client-message-alert.is_open...taxi-client-message-alert.color...taxi-client-ping-pkid-store.data@0ff8f2f02059be5962c2a13a011d56b1..'
~~~~~~~~~~~~~~~~~^^^^^^^^
Traceback (most recent call last):  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/dash/dash.py", line 1303, in dispatch    cb = self.callback_map[output]
[2024-07-28 21:55:51,028] ERROR in app: Exception on /_dash-update-component [POST]
```

Notably, this only occurs on this callback, which is unique in that it is called frequently and contains a duplicate output.

The relevant code is:

```python
@callback(Output(pid.geoloc, 'update_now'),
          Output(pid.message_alert, 'children'),
          Output(pid.message_alert, 'is_open'),
          Output(pid.message_alert, 'color'),
          Output(pid.ping_pkid_store, 'data', allow_duplicate=True),
          Input(pid.refresh_trig, 'n_intervals'),
          State(pid.ping_pkid_store, 'data'),
          State(pid.message_alert, 'is_open'),
          prevent_initial_call = True)
def taxi_client_msg_update(_, pkid_inf, disp):
    ...
    return True, msg, disp, color, pkid_inf
```

It seems similar to this old issue:
https://community.plotly.com/t/dash-2-9-2-keyerror-callback-function-not-found-for-output-does-not-make-any-sence-in-docker/74254

**I suspect it has something to do with the hash that is appended on the end of the allow_duplicate output - perhaps this hash is not generated deterministically in multiple instances of the app.**

**Expected behavior**

Callback triggers consistently and no error messages printed.

**Comment by RobertJN64** [comment]
Never mind - I figured out the issue. I recently upgraded from an older version of dash that used md5 hashing in the callback ids. When a client that was still using the old md5 hash sent a request, the new sha256 hash did not match. The hashing is deterministic and is not related to multiple client versions.

Thank you for maintaining this excellent library!
