### ISSUE TITLE
IE11 in compatibility mode doesn't display favicon.ico from assets directory

### ISSUE THREAD

**Issue by amarvin** [plotly/dash#310]
Favicon isn't shown on my Dash app using IE11 in compatibility mode (common for Intranet apps), although it works well in any modern browser. The favicon isn't even shown if I go to the url `/assets/favicon.ico` .

I think the asset would load correctly, if the asset url included this meta tag
`<meta http-equiv="X-UA-Compatible" content="IE=edge">`
Could this be included in the template or allow something like add_meta for assets?

**Comment by T4rk1n** [comment]
You can add the meta tag directly in the dash constructor:

`app = dash.Dash(__name__, meta_tags=[{'http-equiv': 'X-UA-Compatible', 'content': 'IE=edge'}])`

This tag in particular is on almost every modern page, maybe we should include it by default ?

**Comment by amarvin** [comment]
I already have added the meta tags, but they seem to only get added to the main Dash app template, and not to the assets "send file" template.

**Comment by T4rk1n** [comment]
I don't understand, there is only one template, the assets send file just send static data not html. I'll look into favicon.ico for ie11, maybe it's just not the right `type` attribute for internet explorer. Right now it's `type="image/x-icon"` but I've seen `type="image/PNG" also.

**Comment by T4rk1n** [comment]
Also this might be of interest:
https://stackoverflow.com/questions/122067/favicon-not-working-in-ie

**Comment by amarvin** [comment]
I'll check that out, thanks

**Comment by soerendip** [comment]
I am getting this message on Windows after packaging the tool with `pyinstaller`:

```
Exception on /_favicon.ico [GET]
Traceback (most recent call last):
  File "flask\app.py", line 2447, in wsgi_app
  File "flask\app.py", line 1952, in full_dispatch_request
  File "flask\app.py", line 1821, in handle_user_exception
  File "flask\_compat.py", line 39, in reraise
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "dash\dash.py", line 1148, in _serve_default_favicon
  File "pkgutil.py", line 637, in get_data
  File "c:\users\soere\anaconda3\envs\ms-mint\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 341, in get_data
    with open(path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\soere\\AppData\\Local\\Programs\\MINT\\dash\\favicon.ico'
ERROR:ms_mint.app.app:Exception on /_favicon.ico [GET]
Traceback (most recent call last):
  File "flask\app.py", line 2447, in wsgi_app
  File "flask\app.py", line 1952, in full_dispatch_request
  File "flask\app.py", line 1821, in handle_user_exception
  File "flask\_compat.py", line 39, in reraise
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "dash\dash.py", line 1148, in _serve_default_favicon
  File "pkgutil.py", line 637, in get_data
  File "c:\users\soere\anaconda3\envs\ms-mint\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 341, in get_data
    with open(path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\soere\\AppData\\Local\\Programs\\MINT\\dash\\favicon.ico'``
```

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
