### ISSUE TITLE
proc permission error when executing an app bundled with pyinstaller

### ISSUE THREAD

**Issue by matt-sd-watson** [plotly/dash#3110]
I am attempting to bundle a flask/dash app using pyinstaller and execute it from CLI. The installer is able to bundle correctly, but when i try to executable the file, i get the following error: 

```
 * Serving Flask app 'rakaia.entrypoint'
 * Debug mode: on
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
  File "dash/dash.py", line 1857, in <lambda>
  File "dash/_watch.py", line 35, in watch
  File "dash/_watch.py", line 20, in walk
PermissionError: [Errno 13] Permission denied: '/proc/1/cwd'
```

My spec file is as follows:

```
# -*- mode: python ; coding: utf-8 -*-

import sys ; sys.setrecursionlimit(sys.getrecursionlimit() * 5)

with open('../requirements.txt') as f:
    required = f.read().splitlines()

keep_capital = ['Pillow', 'Cython', 'OpenSSL']

required = [elem.split("==")[0].replace("-", "_") for elem in required]
required = [elem.lower() if elem not in keep_capital else elem for elem in required]


from PyInstaller.utils.hooks import collect_data_files, copy_metadata

additional_deps = []
for extra in required:
    additional_deps += collect_data_files(extra)
    additional_deps += copy_metadata(extra)

all_data = additional_deps + [('../rakaia/templates', 'templates'), ('../rakaia/static', 'static'), ('../rakaia/assets', 'assets')]

block_cipher = None

import distutils.util

COMPILING_PLATFORM = distutils.util.get_platform()
STRIP = False

if COMPILING_PLATFORM == 'win-amd64':
    platform = 'win'
elif COMPILING_PLATFORM == 'linux-x86_64':
    platform = 'nix64'
elif "macosx" in COMPILING_PLATFORM:
    platform = 'mac'

a = Analysis(['../rakaia/wsgi.py'],
             pathex=['./'],
             binaries=[],
             datas=all_data,
             hookspath=[],
             runtime_hooks=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='rakaia',
          debug=False,
          bootloader_ignore_signals=False,
          strip=STRIP,
          upx=True,
          console=True,
          icon='../rakaia/assets/rakaia.ico')

coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=STRIP,
               upx=True,
               upx_exclude=[],
               name='rakaia')

if platform == 'mac':
    app = BUNDLE(coll,
                 name='rakaia.app',
                 icon='../rakaia/assets/rakaia.ico',
                 bundle_identifier=None)
```

and package requirements:

```
anndata==0.9.1
async-generator==1.10
attrs==23.1.0
beautifulsoup4==4.12.2
cachelib==0.9.0
certifi==2024.07.04
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
contourpy==1.0.7
cryptography==43.0.1
cycler==0.11.0
Cython==0.29.35
dash==2.18.2
dash-ag-grid==2.3.0
dash-auth==2.0.0
dash-bio==1.0.2
dash-bootstrap-components==1.4.1
dash-canvas==0.1.0
dash-core-components==2.0.0
dash-daq==0.5.0
dash-draggable==0.1.2
dash-extensions==1.0.1
dash-google-auth==0.1.2
dash-html-components==2.0.0
dash-mantine-components==0.12.1
dash-table==5.0.0
dash-testing-stub==0.0.2
dash-tour-component==0.0.2
dash-uploader==0.7.0a1
dill==0.3.6
diskcache==5.6.1
dnspython==2.7.0
EditorConfig==0.12.3
exceptiongroup==1.1.1
Flask==2.2.5
Flask-Caching==2.0.2
Flask-Dance==7.0.0
Flask-HTTPAuth==4.8.0
fonttools==4.43.0
freeport==0.1.15
glasbey==0.2.0
h11==0.14.0
h5py==3.8.0
idna==3.7
igraph==0.10.4
imagecodecs==2023.9.18
imageio==2.31.0
imctools==2.1.8
importlib-metadata==6.6.0
importlib-resources==5.12.0
iniconfig==2.0.0
itsdangerous==2.1.2
Jinja2==3.1.4
joblib==1.2.0
jsbeautifier==1.14.8
kaleido==0.2.1
kiwisolver==1.4.4
lazy_loader==0.2
leidenalg==0.9.1
llvmlite==0.42.0
lxml==4.9.2
MarkupSafe==2.1.3
matplotlib==3.7.1
mongomock==4.1.2
more-itertools==9.1.0
multiprocess==0.70.14
natsort==8.3.1
networkx==3.1
numba==0.59.0
numexpr==2.8.8
numpy==1.24.3
oauthlib==3.2.2
opencv-python-headless==4.8.1.78
outcome==1.2.0
packaging==21.3
pandas==2.0.2
ParmEd==4.3.0
patsy==0.5.3
percy==2.0.2
PhenoGraph==1.5.7
Pillow==10.3.0
plotly==5.14.1
pluggy==1.0.0
psutil==5.9.5
pycparser==2.21
pydantic==1.10.13
pymongo==4.6.3
pynndescent==0.5.10
pyOpenSSL==24.2.1
pyparsing==3.0.9
PySocks==1.7.1
pytest==7.3.1
pytest-cov==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyWavelets==1.4.1
readimc==0.7.0
requests==2.32.3
requests-oauthlib==1.3.1
scanpy==1.9.3
scikit-image==0.21.0
scikit-learn==1.5.0
scipy==1.10.1
seaborn==0.12.2
selenium==4.2.0
session-info==1.0.0
setuptools==70.0.0
shortuuid==1.0.12
six==1.16.0
sniffio==1.3.0
sortedcontainers==2.4.0
soupsieve==2.4.1
statsmodels==0.14.0
stdlib-list==0.8.0
steinbock==0.16.1
tenacity==8.2.2
texttable==1.6.7
threadpoolctl==3.1.0
tifffile==2023.8.12
tomli==2.0.1
tqdm==4.66.3
trio==0.22.0
trio-websocket==0.10.2
typing_extensions==4.8.0
tzdata==2023.3
umap-learn==0.5.2
urllib3==1.26.19
urllib3-secure-extra==0.1.0
URLObject==2.4.3
waitress==3.0.1
Werkzeug==3.0.6
wheel==0.38.4
wsproto==1.2.0
xmltodict==0.13.0
xtiff==0.7.9
zipp==3.19.1
```

**Comment by matt-sd-watson** [comment]
confirmed that this is solved by setting the dev mode for the dash flask server to False, or switching to waitress
