### ISSUE TITLE
Cannot import dash

### ISSUE THREAD

**Issue by nmiculinic** [plotly/dash#76]
I've installed dash via pip3 on Ubuntu 16.04LTS, however upon importing dash I have huge error popping out:

```
Type "help", "copyright", "credits" or "license" for more information.
>>> import dash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/dash/__init__.py", line 1, in <module>
    from .dash import Dash
  File "/usr/local/lib/python3.5/dist-packages/dash/dash.py", line 3, in <module>
    import plotly
  File "/usr/local/lib/python3.5/dist-packages/plotly/__init__.py", line 31, in <module>
    from plotly import (plotly, dashboard_objs, graph_objs, grid_objs, tools,
  File "/usr/local/lib/python3.5/dist-packages/plotly/plotly/__init__.py", line 10, in <module>
    from . plotly import (
  File "/usr/local/lib/python3.5/dist-packages/plotly/plotly/plotly.py", line 29, in <module>
    from plotly import exceptions, files, session, tools, utils
  File "/usr/local/lib/python3.5/dist-packages/plotly/tools.py", line 16, in <module>
    from plotly import exceptions, optional_imports, session, utils
  File "/usr/local/lib/python3.5/dist-packages/plotly/utils.py", line 27, in <module>
    pandas = get_module('pandas')
  File "/usr/local/lib/python3.5/dist-packages/plotly/optional_imports.py", line 23, in get_module
    return import_module(name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3/dist-packages/pandas/__init__.py", line 42, in <module>
    import pandas.core.config_init
  File "/usr/lib/python3/dist-packages/pandas/core/config_init.py", line 17, in <module>
    from pandas.core.format import detect_console_encoding
  File "/usr/lib/python3/dist-packages/pandas/core/format.py", line 10, in <module>
    from pandas.core.index import Index, MultiIndex, _ensure_index
  File "/usr/lib/python3/dist-packages/pandas/core/index.py", line 31, in <module>
    from pandas.io.common import PerformanceWarning
  File "/usr/lib/python3/dist-packages/pandas/io/common.py", line 68, in <module>
    from boto.s3 import key
  File "/usr/lib/python3/dist-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
  File "/usr/lib/python3/dist-packages/boto/plugin.py", line 92, in load_plugins
    for file in glob.glob(os.path.join(directory, '*.py')):
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```

```
@instance-1:~$ pip3 freeze | grep dash
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
dash==0.17.7
dash-core-components==0.5.3
dash-html-components==0.6.2
dash-renderer==0.7.3
```

**Comment by nmiculinic** [comment]
```plotly==2.0.12```

**Comment by nmiculinic** [comment]
I somehow fixed it; by reinstalling all packages. Since I cannot replicate the issue further I'm closing the issue.
