### ISSUE TITLE
 dash_core_components.__version__ shows "module 'code' has no attribute 'InteractiveInterpreter'"

### ISSUE THREAD

**Issue by yoonghm** [plotly/dash#924]
**Context**

```
dash                               1.2.0
dash-core-components               1.1.2
dash-daq                           0.1.7
dash-html-components               1.0.1
dash-renderer                      1.0.1
dash-table                         4.2.0
```
**Describe the bug**

```
import dash_core_components
```

It shows

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-99015f17851e> in <module>
----> 1 import dash_core_components
      2 print(dash_core_components.__version__)

C:\Home\Anaconda3\lib\site-packages\dash_core_components\__init__.py in <module>
      6 import os as _os
      7 import sys as _sys
----> 8 import dash as _dash
      9 
     10 _basepath = _os.path.dirname(__file__)

C:\Home\Anaconda3\lib\site-packages\dash\__init__.py in <module>
----> 1 from .dash import Dash, no_update  # noqa: F401
      2 from . import dependencies  # noqa: F401
      3 from . import development  # noqa: F401
      4 from . import exceptions  # noqa: F401
      5 from . import resources  # noqa: F401

C:\Home\Anaconda3\lib\site-packages\dash\dash.py in <module>
     20 from flask import Flask, Response
     21 from flask_compress import Compress
---> 22 from werkzeug.debug.tbtools import get_current_traceback
     23 
     24 import plotly

C:\Home\Anaconda3\lib\site-packages\werkzeug\debug\__init__.py in <module>
     29 from ..wrappers import BaseRequest as Request
     30 from ..wrappers import BaseResponse as Response
---> 31 from .console import Console
     32 from .repr import debug_repr as _debug_repr
     33 from .tbtools import get_current_traceback

C:\Home\Anaconda3\lib\site-packages\werkzeug\debug\console.py in <module>
    147 
    148 
--> 149 class _InteractiveConsole(code.InteractiveInterpreter):
    150     def __init__(self, globals, locals):
    151         code.InteractiveInterpreter.__init__(self, locals)

AttributeError: module 'code' has no attribute 'InteractiveInterpreter'
```

It seems that `Code.py` is used by multiple Python packages. Python could not find the intended `Code.py`.

Importing dash alone exhibits the same issue. I am using Anaconda3 2019.07 for Windows 10 on Jupyter Lab. However the issue does not occur for CLI Python. Both Jupyter Lab and CLI uses the same Python executable. Perhaps iPython imported something before that.

I save all Python with dash in file (say `./mydash.py`) and execute them via the following command from a code cell within Jupyter Lab:

```
!python -I ./mydash.py
```

it works as expected then.

**Expected behavior**

It should see the version number.

**Comment by yoonghm** [comment]
However, the example from [https://dash.plot.ly/getting-started](url) would not work even I use `python -I`

For example, `python -I mycode.py`

```
Running on http://127.0.0.1:8050/
Debugger PIN: 595-932-097
 * Serving Flask app "mycode" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "C:\KBS\Python3\mycode.py", line 1, in <module>
    import dash
  File "C:\Home\Anaconda3\lib\site-packages\dash\__init__.py", line 1, in <module>
    from .dash import Dash, no_update  # noqa: F401
  File "C:\Home\Anaconda3\lib\site-packages\dash\dash.py", line 22, in <module>
    from werkzeug.debug.tbtools import get_current_traceback
  File "C:\Home\Anaconda3\lib\site-packages\werkzeug\debug\__init__.py", line 31, in <module>
    from .console import Console
  File "C:\Home\Anaconda3\lib\site-packages\werkzeug\debug\console.py", line 149, in <module>
    class _InteractiveConsole(code.InteractiveInterpreter):
AttributeError: module 'code' has no attribute 'InteractiveInterpreter'
```

**Comment by yoonghm** [comment]
I discover the problem now. I have a folder name `code` with other python code in the working directory of my code. `import code` import this code first rather than the standard `code` module.
